### ISSUE TITLE
Unicode support for custom logging

### ISSUE THREAD

**Issue by NaturalJ0** [microsoft/wil#110]
PCSTR --> PCTSTR

RETURN_IF_FAILED_MSG(E_FAIL, _T("TCHAR")); // not support
RETURN_IF_FAILED_MSG(E_FAIL, L"Unicode"); // not support

e.g

__R_DIRECT_METHOD(void, Return_HrMsg)(__R_DIRECT_FN_PARAMS HRESULT hr, _Printf_format_string_ PCSTR formatString, ...) WI_NOEXCEPT

inline void ReportFailure_Msg(__R_FN_PARAMS_FULL, FailureType type, HRESULT hr, _Printf_format_string_ PCSTR formatString, va_list argList)
        {
            wchar_t message[2048];
            PrintLoggingMessage(message, ARRAYSIZE(message), formatString, argList);
            ReportFailure(__R_FN_CALL_FULL, type, hr, message);
        }

**Comment by dunhor** [comment]
Please see https://github.com/microsoft/wil/wiki/Error-handling-helpers#using-custom-messages

> Be explicit when logging strings with XXXX_MSG macros. Use either: %ls or %hs to control whether an argument is a wide or ascii string, rather than using %s or %S. The format string is expected to be ASCII to minimize binary size, but internally is printed Unicode to avoid loss of data from params. Use the explicit format specifier to avoid the ambiguity this can bring.

**Comment by NaturalJ0** [comment]
Thank you!
