### ISSUE TITLE
token_helpers.h generates compile error unless _WIN32_WINNT >= _WIN32_WINNT_WIN8

### ISSUE THREAD

**Issue by nhutchinson-te** [microsoft/wil#119]
Depending on the value of _WIN32_WINNT, token_helpers.h may generate a compiler error when you include it as it makes use of APIs like GetCurrentThreadEffectiveToken that are only available on Windows 8 and above.

To reproduce:

```cpp
// Define WINVER/_WIN32_WINNT to _WIN32_WINNT_WIN7 
#define WINVER 0x0601
#define _WIN32_WINNT 0x0601
#include <Windows.h>
#include <wil/token_helpers.h>
```

```
wil/token_helpers.h(130,44): error: use of undeclared identifier 'GetCurrentThreadEffectiveToken'
        return tokenHandle ? tokenHandle : GetCurrentThreadEffectiveToken();
                                           ^
wil/token_helpers.h(546,29): error: use of undeclared identifier 'GetCurrentThreadEffectiveToken'
            token ? token : GetCurrentThreadEffectiveToken(),

```

**Comment by sylveon** [comment]
Since wil lives with the OS codebase, it expects a recent OS target.

**Comment by dunhor** [comment]
That's not entirely true. While there may be minimum SDK requirements, there are still a number of projects that target downlevel, both inside and outside the OS codebase, so it's a good idea to conditionalize uses when possible. Feel free to submit a PR that conditionally excludes the parts of the header that are problematic (which seems like a pretty significant amount of the header).
