### ISSUE TITLE
Flow control macros could use [[unlikely]] to hint at hot paths

### ISSUE THREAD

**Issue by jonwis** [microsoft/wil#122]
https://github.com/microsoft/wil/blob/af093723caaa204695b77b90c0d83474f9a6766e/include/wil/result_macros.h#L607

This macro could use https://en.cppreference.com/w/cpp/language/attributes/likely or `__analysis_assume` to hint to various optimizers that "succeeded" is _generally_ more likely than failed.

**Comment by dunhor** [comment]
Isn't `__analysis_assume` strictly used by static analysis tools? I also believe it's used to signal conditions that _are_ true, not things that are _likely_ to be true.

That said, should be easy enough to prepare for C++20 support
```c++
#if __has_cpp_attribute(likely)
#define WI_LIKELY [[likely]]
#else
#define WI_LIKELY
#endif
```
etc.

**Comment by jonwis** [comment]
Closing out. Optimizers are wily creatures. I'll let them do their jobs.
