### ISSUE TITLE
C6011 warning from WIL header file

### ISSUE THREAD

**Issue by davidmatson** [microsoft/wil#126]
See #124 for core repro steps. To repro this case, do:
```c++
#include <wil/result.h>
```

In result.h, there are two lines that trigger warnings such as this one:
C6011: Dereferencing NULL pointer 'Temp_value_#7840'. ...

**Comment by jonwis** [comment]
The analyzer didn't like this:

https://github.com/microsoft/wil/blob/adae42be8f45bdbf0fa50aca000fd8bf2063fff5/include/wil/result.h#L409-L412

The null check is right there, so this looks like a false positive. This makes the analzyer happy:

```c++
if (auto pNewRaw = details::ProcessHeapAlloc(0, sizeof(Node)))
{
    auto pNew = new (pNewRaw) Node{ threadId };
```
