### ISSUE TITLE
The word "because" is spelled wrong on line 22 of result_originate.h

### ISSUE THREAD

**Issue by dmachaj** [Microsoft/wil#13]
The word "Because" is spelled wrong on this line (my bad).

https://github.com/Microsoft/wil/blob/a8fbb33b1cdb706c3fd8941693407bd6e145e0d6/include/wil/result_originate.h#L22

**Comment by dunhor** [comment]
If you don't mind submitting a PR, I'm actually kind of curious to test the CI/etc. system with someone who's not me :)

**Comment by dmachaj** [comment]
I'm not allowed to push a private branch to create a pull request.  Is this expected?

C:\code\wil>git push --set-upstream origin user/dmachaj/fix-typo
remote: Permission to Microsoft/wil.git denied to dmachaj.
fatal: unable to access 'https://github.com/Microsoft/wil.git/': The requested URL returned error: 403

**Comment by dunhor** [comment]
Okay, I was curious about that. I'm guessing administrators only have permission to create a branch. The "typical" way is to fork it and then request that changes be merged in.
