### ISSUE TITLE
Variable-length structs

### ISSUE THREAD

**Issue by gix** [microsoft/wil#130]
This may be a feature request as I couldn't find anything in the documentation about it. Does `wil` provide a way to deal with variable-length (or flexible array-member) structs like `TOKEN_PRIVILEGES`, `ACE`, `TRACE_EVENT_INFO` etc.?

**Comment by dunhor** [comment]
I'm not entirely sure what you're looking for. If there's something specific that you're looking for, GitHub's search works decently well. Otherwise other search tools (e.g. VS Code) work pretty well also. E.g. searching `TOKEN_PRIVILEGES` will lead you to the `token_helpers.h` header.

**Comment by gix** [comment]
Excuse me for being not more specific. I'm talking about replacing the following pattern:

```
ULONG bufferSize;
TdhGetEventInformation(event, 0, nullptr, nullptr, &bufferSize);
TRACE_EVENT_INFO* eventInfo = (TRACE_EVENT_INFO*)malloc(bufferSize);
TdhGetEventInformation(event, 0, nullptr, eventInfo, &bufferSize);
```

The `malloc` can be replaced by `make_unique<byte[]>`, but still requires casting and an additional variable to get the correct pointer type. A `unique_pointer<TRACE_EVENT_INFO>` requires a custom deleter and custom make functions taking the raw size. Since this pattern is so prevalent in the Windows SDK, I had thought or hoped `wil` might have something for this out-of-the-box.

I had already looked through the `token_helpers.h` header and only saw stuff for receiving token information. But when using e.g. `AdjustTokenPrivileges`, one has to allocate a variable-sized `TOKEN_PRIVILEGES` structure. Looking closer, `get_token_information_nothrow` goes through exactly those contortions I'm speaking about (and using `::operator new` to allocate but `delete obj` to free is probably undefined behavior).
