### ISSUE TITLE
Last error lost when calling LOG_*() macros

### ISSUE THREAD

**Issue by yves-dolce** [microsoft/wil#131]
I've not tested all of the error logging macros but by looking at the underlying `ReportFailure<T>()`, you're not using your own `wil::last_error_context()` to preserve the last error.
In that function, this call is resetting the error to 0 for me:
`failure->pszModule = (g_pfnGetModuleName != nullptr) ? g_pfnGetModuleName() : nullptr;`

Is this by design (i.e. one doesn't pay for things she doesn't ask for) or you've never had a need for the last error code after logging it?

Thanks.

**Comment by JamesWCCheng** [comment]
I've met the same issue.

If this by design, can you provide the intention of the design?

thanks

**Comment by dunhor** [comment]
Probably just an oversight. I suspect nobody's noticed/cared since `LOG_*` is generally the "end of the road" for the error code. Feel free to submit a PR
