### ISSUE TITLE
resource.h doesn't compile with WINVER=0x0600

### ISSUE THREAD

**Issue by CookiePLMonster** [microsoft/wil#134]
Technically, as per the "Update WINVER and _WIN32_WINNT" article from MSDN, targetting Windows Vista is an unsupported scenario, however in WIL headers it's implied to be the minimum supported version:

```cpp
// Minimal requirement set to Windows Vista
#if NTDDI_VERSION < NTDDI_VISTA 
#error WRL requires NTDDI_VERSION to be #defined at least to NTDDI_VISTA or greater
#endif
```

For `resource.h`, this is untrue however - attempting to include it and use it when targeting Vista throws a compilation error in `slim_event_t`, even if said feature is not used:
```
error C3861: 'QueryUnbiasedInterruptTime': identifier not found
```

Fix seems easy enough - this class is already guarded with the following preprocessor directive:
```
#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP)
```

and so extending it to exclude systems older than Windows 7 allows the code to compile:
```
#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP) && NTDDI_VERSION >= NTDDI_WIN7
```

EDIT:
This change is trivially PR-able, but does it require test coverage too? Windows 7 has test coverage, but since Vista is technically an unsupported target I would expect it not to require similar coverage and a best effort "support" might be sufficient.

**Comment by dunhor** [comment]
@ChrisGuzak may know more about existing consumers' needs, but I'm inclined to say that Win7 is as low as we're committed to explicitly supporting at this time. Also keep in mind that WIL is somewhat old, so the check against Vista may very well just be something that nobody ever cared to update.

That said, it seems perfectly reasonable that if the scenario is important to some consumers, we'd allow them to submit fixes to properly ifdef things away, with the expectation that things may break again in the future as changes are made (and thus, I would suggest against adding tests for it)

**Comment by CookiePLMonster** [comment]
> That said, it seems perfectly reasonable that if the scenario is important to some consumers, we'd allow them to submit fixes to properly ifdef things away, with the expectation that things may break again in the future as changes are made (and thus, I would suggest against adding tests for it)

That sounds like a reasonable solution to me. I don't think anyone would be surprised that no full support for Vista can be guaranteed, but I personally like the approach of not deliberately cutting off older systems unless there is a very good reason for it - and with WIL, it does seem like all but two features (as shown by my PR) can still be "offered" to apps targeting Vista.
