### ISSUE TITLE
wil::unique_array with elements on the stack

### ISSUE THREAD

**Issue by CookiePLMonster** [microsoft/wil#140]
When dealing with COM types `WRL::ComPtr`, `wil:com_ptr`, as well as `wil::unique_array_ptr` for handling arrays returned from WinAPI calls.

But...

To my best knowledge, there is no way to cleanly operate on arrays of COM pointers which are located on the stack, which e.g. is a common idiom in D3D. This creates two separate problems, which I'll briefly describe separately.

## Setters
For cases where "arrays" have only one element, using managed pointers is easy - my examples use `WRL::ComPtr` but naturally they have equivalent semantics in `wil::com_ptr`:

```cpp
ComPtr<ID3D11RenderTargetView> myRTV;
ComPtr<ID3D11DepthStencilView> myDSV;
context->OMSetRenderTargets( 1, myRTV.GetAddressOf(), myDSV.Get() );
```

However, problems arise when trying to operate on actual arrays with more than one element. As far as I can tell, currently the only way to do it is to employ an intermediate array with raw pointers:

```cpp
ComPtr<ID3D11RenderTargetView> myRTVArray[3];
ComPtr<ID3D11DepthStencilView> myDSV;

ID3D11RenderTargetView* const tmp[] = { myRTVArray[0].Get(), myRTVArray[1].Get(), myRTVArray[2].Get() };
context->OMSetRenderTargets( _countof(tmp), tmp, myDSV.Get() );
```

An imaginary `wil::unique_array` could simplify semantics to be similar to `std::array`, but with extra awareness of managed objects:
```cpp
wil::unique_array<ComPtr<ID3D11RenderTargetView>, 3> myRTVArray;
ComPtr<ID3D11DepthStencilView> myDSV;

context->OMSetRenderTargets( myRTVArray.size(), myRTVArray.get(), myDSV.Get() );
```

## Getters

The situation for getters is similar, but as far as I can tell it's a bit more complicated. For operating on a single object, the situation is identical to setters so I'll skip that. For multiple elements, to *get* an array of COM objects, they need to be first stored to an array of raw pointers and attached to an array of `WRL::ComPtr` or `wil::com_ptr`:
```cpp

ID3D11ShaderResourceView* tmp[5];
context->PSGetShaderResources( 0, _countof(tmp), tmp );

ComPtr<ID3D11ShaderResourceView> views[5];
ID3D11ShaderResourceView** tmpPtr = tmp;
for ( auto& view : views )
{
    view.Attach(*tmpPtr++);
}
```

This is error prone and unnecessarily verbose. An imaginary `wil::unique_array` could simplify this code to:
```cpp
wil::unique_array<ComPtr<ID3D11ShaderResourceView>, 5> views;
context->PSGetShaderResources( 0, views.size(), &views );
```

***

From what I have seen, this feature is technically possible to emulate via `wil::unique_any_array_ptr`, with an empty `ArrayDeleter` and an appropriate `ElementDeleter`. However, I haven't tried implementing this in practice so I'm not sure if it can have any pitfalls. It also requires the "array view" to be a separate variable to the actual array, which I imagine could cause confusion regarding the object ownership.

**Comment by CookiePLMonster** [comment]
Note to self or those who might be concerned by this issue - this suggestion requires functionality to convert `ComPtr<T>[]` to `T*[]` which could probably be done by typecasting. However, that would likely be UB, so it might make more sense to employ a "middleman" temporary class which populates smart pointers (or not) from its own destructor. According to the docs, WIL already does something very similar with [wil::out_param](https://github.com/microsoft/wil/wiki/RAII-resource-wrappers#wilout_param).

**Comment by CookiePLMonster** [comment]
Alternate idea, I apologize if posting so many comments in a row is not appropriate for this repository:

Given how `wil::out_param` tries to accommodate for different types of smart pointers, on the second thought maybe the easiest and wisest idea would be to just introduce two functions (which use classes internally):

* `wil::out_array_param` which takes either `smart_ptr<T>, size_t` or `smart_ptr<t>[N]`, instantiates an empty `T*[N]` array, passes the pointer to that array instead and uses `attach_to_smart_pointer` on every array element in its own destructor.
* `wil::in_array_param` which which takes either `smart_ptr<T>, size_t` or `smart_ptr<t>[N]`, instantiates an `T*[N]` array and populates it with `com_raw_ptr` (no need to claim ownership). It does nothing in its own destructor, because it wouldn't take ownership of COM pointers in the first place.

As far as I can tell now, it would handle all cases regarding arrays of COM objects. It might require extra boilerplate to eg. manage an array of `unique_handle` (for example, for `WaitForMultipleObjects`), but `wil::out_param` might not be handling those currently either.

**Comment by DBJDBJ** [comment]
This requires a few diagrams me thinks ... But, there is none to be seen. Anywhere in here.

**Comment by CookiePLMonster** [comment]
I found out that since posting this issue, a new Wiki page appeared, covering this specific use case and proving that no additional functionality is required:
https://github.com/microsoft/wil/wiki/Waiting-on-kernel-objects#waiting-on-multiple-objects

While this page only mentions `wistd::unique_handle` classes, I am almost sure the same assumption can be made about `WRL::ComPtr` and `wil::com_ptr`. With this in mind, I believe this issue is now not relevant anymore.
