### ISSUE TITLE
RAII wrappers for RegisterWaitForSingleObject / UnregisterWaitEx

### ISSUE THREAD

**Issue by bgianfo** [microsoft/wil#146]
Has there been any thought into the possibility of creating RAII wrappers for the register/unregister wait API's? 

- [RegisterWaitForSingleObject](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-registerwaitforsingleobject)
- [UnregisterWait/UnregisterWaitEx](https://docs.microsoft.com/en-us/windows/win32/sync/unregisterwaitex)

It looks like adding a wil::unique_any typedef to just pass UnregisterWaitEx wouldn't be enough, as UnregisterWait can return **ERROR_IO_PENDING** which would need to be bubbled back to the caller?

**Comment by dunhor** [comment]
> UnregisterWait can return ERROR_IO_PENDING which would need to be bubbled back to the caller

Destructors can't really communicate that type of information. Do you have a better idea of what you're looking for in such a type?

**Comment by bgianfo** [comment]
I'll just close this or now... I'll re-open if I have time to put more thought into this. Thanks!
