### ISSUE TITLE
wil event RAII types don't support alertable waits

### ISSUE THREAD

**Issue by smaillet-ms** [microsoft/wil#152]
wil::event_t relies on the wil::handle_wait function which uses WaitForSingleObjectEx with a hardcoded alertable flags set to FALSE, this prevents the use of wait for async I/O scenarios. Forcing apps to "get" the raw hjandle and call WaitForSIngleObjectEx directly. This is inconsistent with the mutex, semaphore and other objects that do have the alertable flag exposed.

Possible solution:
Add the alretable flag with a default of FALSE to wil::handle_wait() AND the event_t::wait() so that existing apps get the same functionality they always got, but new code can specify the wait.

**Comment by sylveon** [comment]
Opened #153 for this
