### ISSUE TITLE
Error C2440 in result_macros.h

### ISSUE THREAD

**Issue by zainali9** [microsoft/wil#155]
Hi, I am fairly new to desktop apps so this might be a stupid question. But I follow all the steps of the Sample App and yet get the following error

>> webview2samples-master\gettingstartedguides\win32_gettingstarted\packages\microsoft.windows.implementationlibrary.1.0.200902.2\include\wil\result_macros.h(1225): error C2440: 'return': cannot convert from 'initializer list' to 'wil::details::ResultStatus'

Not sure what I missed. I am using vs2015 (v140), Target platform Version: 10.0.17763.0, Target platform: Windows 10

**Comment by zainali9** [comment]
Update: Everything is running fine in vs2019 with target sdk: v140 and platform Win 10. Problem only in vs2015 of before

**Comment by dunhor** [comment]
I'm unsure if anyone's used WIL with 2015 in recent history, so it wouldn't surprise me if it has fallen out of support

**Comment by zainali9** [comment]
So if my main project is in vs2015, and I need to make a dll/exe project for WebView2 use, I wouldn't be able to use WebView2 unless I update it to vs2019?

**Comment by dunhor** [comment]
> I wouldn't be able to use WebView2

I'm not familiar with WebView2; what part of it requires using WIL?

**Comment by zainali9** [comment]
Unsure about that but need to include these two following headers:
#include <wrl.h>
#include <wil/com.h>

It uses webController:-
static wil::com_ptr<ICoreWebView2Controller> webviewController;

**Comment by dunhor** [comment]
> need to include these two following headers:

Is this "need" coming from WebView2 itself? Or are you just following an example, etc? E.g. why can't you just use WRL's `ComPtr` type?

**Comment by zainali9** [comment]
I am following an example of a sample app for Microsoft WebView2 @ https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/win32. Figuring out how much need there is of it.

**Comment by sylveon** [comment]
There is not a specific need for `wil::com_ptr`, it's just what the sample uses: you can use `Microsoft::WRL::ComPtr` instead

**Comment by zainali9** [comment]
Oh great! That works, thanks a lot :-)
