### ISSUE TITLE
cppwinrt winrt::com_ptr vs wil::com_ptr

### ISSUE THREAD

**Issue by mediabuff** [microsoft/wil#156]
When to use either of these com smart pointers ? Any best pratice/recommendations.

**Comment by sylveon** [comment]
They're both nearly functionally equivalent. Personally I use `wil::com_ptr` where I can, but there are places where C++/WinRT exposes bare `winrt::com_ptr` (like `try_as` or `make_self`), so I just use `winrt::com_ptr` in those places.

**Comment by jonwis** [comment]
No official guidance on which to use, really.  @sylveon 's rule of thumb is fine.  Another way to look at it is that C++/WinRT assumes a codebase is all-in on modern C++ support (recent compiler version, support for exceptions, use of STL/std).  By comparison WIL supports codebases that prevent use of exceptions (`wil::com_ptr_failfast`, `wil::com_ptr_nothrow`) where C++/WinRT couldn't be (easily) introduced.

So If you're using C++/WinRT in your codebase (and why not!) stick with `winrt::com_ptr` ... if you're in a space that can't support it, use `wil::com_ptr`.
