### ISSUE TITLE
wi::critical_section for use with std::lock_guard

### ISSUE THREAD

**Issue by mediabuff** [microsoft/wil#158]
Support std::lock_guard

error C2039: 'unlock': is not a member of 'wil::critical_section'
```

// Declared:
using critical_section_guard = std::lock_guard<wil::critical_section>;

// Definition:
wil::critical_section            m_csSubscriptions;

// scoped usage:
{
   critical_section_guard subscriptionsLock(m_csSubscriptions);
}

```

**Comment by sylveon** [comment]
You don't need `std::lock_guard`, use `auto lock = m_csSubscriptions.lock();`

**Comment by mediabuff** [comment]
Thank you. I understand. Having an 'unlock' member would make it more a standard pattern.

**Comment by sylveon** [comment]
If this where to be added, `std::lock_guard` will call `cs.lock()`, returning a RAII object, that object then being immediately destructed and releasing the lock. The API would need to be broken for this to be fixed, but it should be easy enough for you to write your own wrapper around critical section which is usable with standard lock guards:

```cpp
class critical_section
{
public:
    critical_section(const critical_section&) = delete;
    critical_section(critical_section&&) = delete;
    critical_section& operator=(const critical_section&) = delete;
    critical_section& operator=(critical_section&&) = delete;

    critical_section(ULONG spincount = 0) noexcept
    {
        // Initialization will not fail without invalid params...
        InitializeCriticalSectionEx(&m_cs, spincount, 0);
    }

    ~critical_section() noexcept
    {
        DeleteCriticalSection(&m_cs);
    }

    void lock() noexcept
    {
        return ::EnterCriticalSection(&m_cs);
    }

    void try_lock() noexcept
    {
        return TryEnterCriticalSection(&m_cs);
    }

    void unlock() noexcept
    {
        LeaveCriticalSection(&m_cs);
    }

private:
    CRITICAL_SECTION m_cs;
};
```

**Comment by dunhor** [comment]
@sylveon is correct. The WIL mutex types use a different locking paradigm than the STL that effectively make them incompatible. If you want to use the STL's `std::*lock*` types, then you'll want to use the STL's mutex types or roll your own if you need access to the underlying primitives
