### ISSUE TITLE
wil::vector_range::vector_iterator operator - is incorrect when subtracting iterator points to a higher element

### ISSUE THREAD

**Issue by dimhotepus** [microsoft/wil#160]
`vector_iterator::operator -` is defined as:

```
ptrdiff_t operator-(const vector_iterator& other) const
{
    return m_i - other.m_i;
}
```

where `m_i ` is declared as: `unsigned int m_i`.

Assume `vector_iterator A` points at element with index greater than `vector_iterator B` and we subtract `A` from `B`.
Due to well defined unsigned arithmetic such operation is equivalent to `(UINT_MAX + 1 + B.m_i - A.m_i) % (UINT_MAX + 1)`, which is always `unsigned` and, hence, the `operator-` never returns less than zero result, which is unlikely to be expected.

For x86-64 we can perform well-defined cast `unsigned` -> `ptrdiff_t` for `m_i`, as `ptrdiff_t` is signed with `8+` bytes long.
Unfortunately, for x86 such cast can lead to UB due to `ptrdiff_t` overflow for `unsigned` values > `INT_MAX`.

May be i missed something and this behavior is expected?

**Comment by jonwis** [comment]
Looks like:

https://github.com/microsoft/STL/blob/a10865713d9958f48819fea855bb58a357a620eb/stl/inc/vector#L105-L133

In debug mode, `A - B` would throw a "cannot seek before begin", or otherwise silently plunk you wherever that indexing happened to land you.

**Comment by dimhotepus** [comment]
> Looks like:
> 
> https://github.com/microsoft/STL/blob/a10865713d9958f48819fea855bb58a357a620eb/stl/inc/vector#L105-L133
> 
> In debug mode, `A - B` would throw a "cannot seek before begin", or otherwise silently plunk you wherever that indexing happened to land you.

Yep, looks like it is. Thank you!
