### ISSUE TITLE
wil::GetModuleFileNameW - string size is not adjusted

### ISSUE THREAD

**Issue by m417z** [microsoft/wil#163]
Here's a snippet that demonstrates the issue:

```cpp
#include <windows.h>
#include <string>
#include <iostream>
#include "wil/stl.h"
#include "wil/win32_helpers.h"

int main()
{
    std::wstring exePath = wil::GetModuleFileNameW<std::wstring>(nullptr);
    std::wcout << exePath << '\n';
    std::wcout << exePath.length() << '\n';
    std::wcout << wcslen(exePath.c_str()) << '\n';
}
```

An example output:
```
C:\Users\User\source\repos\ConsoleApplication1\x64\Release\ConsoleApplication1.exe
127
82
```

As you can see, the string size is not adjusted after calling `GetModuleFileNameW` internally.

By the way, if you remove `#include "wil/stl.h"` and try to compile in Release, the compiler crashes. I reported about it in the compiler feedback.

**Comment by m417z** [comment]
@jonwis this code looked strange to me:
https://github.com/microsoft/wil/pull/165/files#diff-d37b3eafe71ceccb982be31eccd9c519a718ce9ef557eaaedcdc94225c3467b3R306-R325

Specifically, I didn't find any reference in the docs to the off-by-one difference that explains `copiedCount` versus `copiedCount + 1` for `GetModuleFileNameExW` vs. `GetModuleFileNameW`, respectively.

And indeed, looks like the fix doesn't work properly with `GetModuleFileNameExW`.

Take the snippet above and replace:
`wil::GetModuleFileNameW<std::wstring>(nullptr);`
with:
`wil::GetModuleFileNameExW<std::wstring>(GetCurrentProcess(), nullptr);`

You'll see that the returned path has its last character missing.

**Comment by jonwis** [comment]
Indeed, I get "{...}.ex" instead of the expected "{...}.exe", thanks. Time to improve the tests and fix the code!
