### ISSUE TITLE
C++ Standard Level Required

### ISSUE THREAD

**Issue by paulushub** [microsoft/wil#183]
Sorry if available somewhere, but I could not find any information on this in the documentations. 
What is the C++ standard level required by this library? Is this fixed or as long as VS 2019+ can handle?

**Comment by sylveon** [comment]
I believe wil can go down all the way to C++11

**Comment by paulushub** [comment]
OK! I decided to give it a test, compiling the `WebView2Browser` sample application with VS 2015, which by MS and Wikipedia fully supports C++ 11. 
I found an unofficial Nuget package for **CPP-REST**, since MS is not providing one for the VS 2015, and updated **WIL** to the latest. The build is currently failing with the error below:
> ...include\wil\result_macros.h(1225): error C2440: 'return': cannot convert from 'initializer list' to 'wil::details::ResultStatus'
