### ISSUE TITLE
Report error with custom parameters?

### ISSUE THREAD

**Issue by stevenwdv** [microsoft/wil#187]
I wanted to make a function that calls the `THROW_WIN32` macro because I want to give it a shorter more convenient name that can then also be used with a `using` statement (related to #186). But then the context information will be incorrect, so I have to pass that around.
Hence my question: is it currently possible to report an error with manually provided parameters, for example:
```cpp
throwWin32(returnAddr, line, file, func, GetLastError());
```
We can of course use `__R_FN(Throw_Win32)(...);`, but using such an internal function seems like asking for trouble, and the signature is dependent on the `RESULT_DIAGNOSTICS_LEVEL`. Is there another way? If not, should maybe public functions be added that take all context parameters and can be called like this?

I guess that maybe I could just disable extra context because I use `CaptureStackBackTrace` anyways, but I imagine that I'm not the only one that doesn't like using the macros.

**Comment by ChrisGuzak** [comment]
AFAIK no way to do this. we look forward [std::source_location](https://en.cppreference.com/w/cpp/utility/source_location) but that is not used in wil yet.
