### ISSUE TITLE
Is this the Windows Internal Library rebranded?

### ISSUE THREAD

**Issue by riverar** [Microsoft/wil#19]
Trying to determine if this is a subset of the Windows Internal Library (with a new name) or a completely different project. It appears to be a subset, sans certain types related to staging configuration, velocity, and the like.

**Comment by kennykerr** [comment]
Correct, this is _that_ WIL with a new name. :wink: 

There are a few omissions - that aren't necessarily useful outside of the OS build environment - but for the most part this is just an open source copy of WIL.

**Comment by riverar** [comment]
Thanks @kennykerr
