### ISSUE TITLE
Should `wil::unique_any_t` constructor be conditionally `noexcept`?

### ISSUE THREAD

**Issue by stevenwdv** [microsoft/wil#191]
I noticed how the `unique_any_t` constructor is not `noexcept` even when the storage constructor is `noexcept`. Is this intentional, and if so, why? A comment does note "`should not be WI_NOEXCEPT (may forward to a throwing constructor)`", but couldn't the `unique_any_t` constructor be declared as:
```cpp
template <typename arg1, typename... args_t>
explicit unique_any_t(arg1 && first, args_t&&... args) noexcept(noexcept(storage_t(wistd::forward<arg1>(first), wistd::forward<args_t>(args)...))) :
	storage_t(wistd::forward<arg1>(first), wistd::forward<args_t>(args)...)
{ ... }
```

Just one example where it could be `constexpr` is `wil::unique_hmodule`, but I'm not even sure if WIL currently has any throwing constructors - does it?

**Comment by ChrisGuzak** [comment]
your suggested change looks good to me. post a PR if you want it.

**Comment by sylveon** [comment]
I've always felt these forwarding constructors to be redundant when we can write `using storage_t::storage_t;` to bring in constructors from the base class. Maybe just use that instead?

**Comment by stevenwdv** [comment]
See #223 & [Azure build](https://dev.azure.com/msft-wil/Windows%20Implementation%20Library/_build/results?buildId=420&view=logs&j=ab477ad6-9781-5b54-82ca-a0141b26726e&t=8fddd505-58bd-5f5a-42fd-95acd1c9abe1&l=181): apparently we cannot use a protected constructor like this, even when we are a derived class. Does anyone know if there is another way to do this? MSVC apparently does permit this when qualifying the name, but other compilers do not, and this would not work with templates as used here. The suggestion of @sylveon does not seem to work either, as the constructor remains protected. One *can* use the `using` method and add a constructor with a *different* signature of which the `noexcept` spec references the inherited protected constructor, but this is undesirable and would also expose any other (public) constructors that the base class may have.

[Here](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGIABwA7KSuADJ4DJgAcj4ARpjEIGYArKQADqgKhE4MHt6%2BAcEZWY4C4ZExLPGJKbaY9qUMQgRMxAR5Pn5BdQ05za0E5dFxCUmpCi1tHQXdEwNDldVjAJS2qF7EyOwcyAYKCgDUAIIHJoFWGkdpxKgEmA6Y6CAmlwdvxxCxqJ7LBwyomFUWzSBFO5zOABEXlcvLFaHhkM9Xu8jp9vrRSAcvj8/gCgZgQWCrIEIQcAPRkg4AMRIB3QZix9VQAHdoZCTABmC5HaG7Jj7A4WA4gA5pWHw5DHInQsVwhFIk7vCxozxY37/QHAggQDX4kEQVGxZbG4UfI3SknkynYYg3RKim53B7oaHvQUQCIETHY2hq3Gagna3Vag0gECG42/EURi2kikHACyQgAam4RagANacoW3BAJBQihJ2tkk7Nsy53FhpAx3TluPkCgD6PI52F5e0OblNsolB2b0suPflrvebhVvvNwcDOrxIebn0jpvn5rOxLj1ttJBF11u9zuLuRbzHnu96L9U/1F%2B1zbDy8XIrvsatBxtxcu7K55aOlerTFrHPrDs%2BxbNtLgbQ5SW3cUEWAgdFTeLwsiMYDbxbIV4yOWgFFQA5AWKTBDiHSU0AYCZiC8IhiAUTElEwRlaBZGVoMREc3ghD1BFPVVJ1nacrwgdijRNEVBN%2BVdIWfAB1EgM0OWIKLpPAqCoBJGFBLJgGYAgNkwEsoU/d8K0wKsa10gDwOAzlQKOCzsG7ZjYPEwdmIVN1EIiYAUJAZts2fHcnX3A4SLIrwHFpYhjKYCJCMdPdHj0stDO/Yzf3/QD%2BUOHzW3bDLqXsuVJX7Jz4IOdzkJvby0KYgrXPeKlx3PXjLya7V6qEqNgIXJ941fEhMQihQNiyAA3XT31LAyeUuT0DhYKKGAgMTwUPA43DrECgq4CACHIzBViCswIA0TEdq8PbEpK/S3A29AtuOg5Tr2zF6W23aTt234yQAKm%2BNJqIOCI82IQhHjAMAvrJC63TbACNswV6zuWXyes3e1/Lig8SqpdarIOKgEfOyb2UuDhVloThkl4PwOC0UhUE4NbLGsA5sI2LZTjMDkeFIAhNFJ1YMxADl/AAOg0SRAjMfwOQ5ABOQIOQ0MxZbMfROEkKm%2BbpzheALY7eZp0nSDgWAYEQFBUCrOgEnISg0Ct%2BhEmALguFVmhaDuKjKFiLXYgiVoAE9OG5%2B22EEAB5BhaCDw3SCwOajHEWP8Aihw8FGgtY8Be4KO2bnPXqLX4ViYhA48LAtZ2vAWGDo2qAMYAFGTPBMGZcO0kYWuZEEEQxHYKRu/kJQ1C13QuH0QxjGsax9DwWIC0gVZUBBHJM4AWgmF0OQhUwmcsMwNAONfw45XX6j3HIXAYdxPE6PQwgiYYqlGcfimyARpj8V/MnfhgFhGRI487AXwEP0KYt8ChAPPmnUBkxBiP0WC/WwcDP56DmG0f%2Bz9AGrFZpsfuPMIp5yNuTDglNSDU1pvTDgqh/AADY160MkAcYAyBJQuxFgyCAjMrCWExLgQgtJzBc0xB4B2CQOZc2WLwA2WhjSkEFmYLgItZYcmSFwWhtDZay0kFwDQtCNDaLVhwDWpAa7JFoSLfRGi9FWNseLchWsqG6xAPrPmqwTbm3WAQMUXoKAQHtmka2gCQj4EonofgPdRDiFloPRQKh1Cxx2pgIhpBmSlzSG4oxZCKG8CoeHCiPiDioCoAcGh9DGHMNYQcdhnDRGBMdhIrgUieZuNWHmJgWBEiLSMSYmukgOQizljLFRQzRmy1oQ42OTjbAuJaYbORCiNAiy4P4FR/hJBBH8EEZIst1lGNPpMyhOs5myONmbDxEAkABKCbbfxlt6mjD5EYRsp0GAZj4HQT2BZPi%2B39sQGOIdLZhwIJHaOWt46TyTrTFOF8M5a2zsgXOXcC4kNpsXUu/zy7bFplXGu3A64Nybi3NuHdqbcwicIKJ/dpAUriSPWOuhVYGCMCgaevDi4L26cvRo69N6ch3myiwB8j6b2Lvy4uu8eFCmPgc4BMC/AQFcKg8eD8KgAL0G/Royr0g/0aJgpYUDeiwIGNquVjQwHwLVVgtBKCIFf2QfMBB6qmlrDZvgpJRCyYU01lMzgZSGFMKeZ5BGbzfhcMFXw0JgjObj1WvcoJEizDNJkfzeRQsBky0zVm7NEySG9JAOYkWkhzHFsYSWktEycnaw4M41x8yznwEuSALxPjbnXMdkkEJAjgkUt7uIXRsTh4JJxYQruaSmAZPrSQ7JjjOD5O8QpYppS6EBqCsy4NryMxhrqQmoRSbpGtNIO0zplAvXGN4H0gZyR%2BnXtUTe%2B9hzcnHL1ic1NgsVki38BoaWyQD4ck0bsiW%2ByfVHJra%2B9x5zzlXPjY7NtMHRjDWQGkNIjZhpcFlo2UyExGyqEYR8j2%2BZva/OYP8ruoc1KgpjtCyKidsW8BhWnOFWdVA5zuMiwQhdY7orLhgOjBDq611WPXJgjdm6t3bp3fFg8%2B3UsHfE0eQsJ4sslTPDl8Al4rwEJnMkm9WV7wsFh0EZJw5mDPkahVSq7X32vvqpBmqcjavs2UJ11rDUgKaLa/I9qzV9DgbZ4J6D2hWaAX5lzBqcHrDwXoD1gmskgafdQipLAFCIYOGh2WItDMHHDfpyN3bGkiPg8QCRHJk2HoUakPNF6C3JE/ckZI/h6uNYa011IVbpkvpTRBxtSAW0UTg2IxIHIu1hPHr2qlIAYm0qHZXUdUnx2TtOdO%2BL1b52FKXbhphyXUvpcy3%2BAioIuFFZK2V%2BZbTMAdNGN0qrpiQCSEkMs%2B7UgdFPae212dYHOvlaSGYZR175bjLof4MwZhGHDZIQc9rxyutntM4%2B6tB6zukFGlRS%2BkggA) are the options I tried and why they don't work.
