### ISSUE TITLE
Detailed logs without system path (RESULT_DIAGNOSTICS_LEVEL)

### ISSUE THREAD

**Issue by justanotheranonymoususer** [microsoft/wil#200]
The default value of `RESULT_DIAGNOSTICS_LEVEL` is `3`, which means that system paths are compiled into the binary. I'd like to avoid that, since I don't want for the build to depend on the project path, and because of size bloat.

https://github.com/microsoft/wil/blob/master/include/wil/result_macros.h#L265

Other possible values:
```cpp
(RESULT_DIAGNOSTICS_LEVEL >= 2) // line number
(RESULT_DIAGNOSTICS_LEVEL >= 3) // line number + file name
(RESULT_DIAGNOSTICS_LEVEL >= 4) // line number + file name + function name
(RESULT_DIAGNOSTICS_LEVEL >= 5) // line number + file name + function name + macro code
```

So currently, to avoid the system file path ending up in the binary, I must select `2`, which is very terse.

I'd like one of the two options:
* Have the relative path, not the full path, of the source file. The library relies on `__PATH__`, and it sounds more like a task for the compiler. See also the topic on StackOverflow: [`__FILE__` macro shows full path](https://stackoverflow.com/q/8487986).
* Have an option for `line number + function name`. Usually it gives much more context than only the line number, obviously.

**Comment by sylveon** [comment]
You can use `/d1trimfile` to remove paths from the `__FILE__` macro, turning it relative. Example use here:

https://github.com/TranslucentTB/TranslucentTB/blob/4b4b41466f2950e9c8fa686e18ffa43ebb1208eb/Common/CppProject.props#L90-L92

**Comment by justanotheranonymoususer** [comment]
Wow, it's barely documented. Thank you!

**Comment by ysc3839** [comment]
@sylveon Is that working for vcpkg packages? IIRC vcpkg compiles packages to dll/lib, didn't that file location hardcoded in dll/lib?

**Comment by sylveon** [comment]
wil is header-only, so when using wil from vcpkg it isn't an issue (although you might have to add the path to vcpkg's installed folder as another `/d1trimfile` command). If a package from vcpkg is using wil, you'll have to make a custom build triplet that passes `/d1trimfile`.

**Comment by ChrisGuzak** [comment]
seems like you reached a conclusion, so I'm closing. thank you @sylveon.
