### ISSUE TITLE
wil::init_once_nothrow example in Win32 helpers is wrong

### ISSUE THREAD

**Issue by Alex-Rose** [microsoft/wil#219]
This is a documentation bug.

In the wiki example, the functor should have an `HRESULT operator()` method which it currently doesn't have. Additionally the parentheses are unmatched
Example should look like this:
```
INIT_ONCE g_init{};
ComPtr<IFoo> g_foo;

HRESULT MyMethod()
{
    bool winner = false;
    RETURN_IF_FAILED(wil::init_once_nothrow(g_init, []
    {
        ComPtr<IFoo> foo;
        RETURN_IF_FAILED(::CoCreateInstance(..., IID_PPV_ARGS(&foo)));
        RETURN_IF_FAILED(foo->Startup());
        g_foo = foo;
        return S_OK;
    }, &winner));
    if (winner)
    {
        RETURN_IF_FAILED(g_foo->Another());
    }
    return S_OK;
}
```

Optionally the lambda could have an explicit return type.

**Comment by ChrisGuzak** [comment]
I fixed it, please check my work. https://github.com/microsoft/wil/wiki/Win32-helpers

**Comment by Alex-Rose** [comment]
Thanks Chris, this is more of a nit than anything but `RETURN_IF_FAILED(::CoCreateInstance(..., IID_PPV_ARGS(&foo));` is missing a closing parenthesis. 
At least with the return type the lambda is correct, the example CoCreate is not the interesting part of this example so feel free to ignore my comment.
