### ISSUE TITLE
Doubt regarding error policy

### ISSUE THREAD

**Issue by demberto** [microsoft/wil#245]
Consider this code:

```cpp
auto factory = wil::CoCreateInstance<AppxFactory, IAppxFactory>(CLSCTX_INPROC_SERVER);
auto stream = wil::com_ptr<IStream>();
if (FAILED(SHCreateStreamOnFileEx(m_path.c_str(), STGM_READ | STGM_SHARE_EXCLUSIVE, 0, FALSE, NULL, &stream)))
	throw StreamCreationFailed();
if (FAILED(factory->CreatePackageReader(stream.get(), &m_reader)))
	throw ReaderCreationFailed();
if (FAILED(m_reader->GetManifest(&m_manifest)))
	throw ManifestReadFailed();
```

If, say, `factory->CreatePackageReader` fails, will it throw an exception or just return the code simply? The docs have examples like these where its shown that it will throw exceptions. My question is how is this even possible with C++, since I call a method from the pointer? When exactly is this error policy useful and how?

Also, there are a few stream helpers, are they for use with `IStream`?

**Comment by dunhor** [comment]
I assume you're referring to the error policy on the `com_ptr_t` type? If so, the error policy relates to operations on the `com_ptr` itself. E.g. `ptr.as<IOtherInterface>()`, etc.
