### ISSUE TITLE
Build Error from #257

### ISSUE THREAD

**Issue by nibanks** [microsoft/wil#259]
We just got a dependabot PR into XDP (https://github.com/microsoft/xdp-for-windows/pull/92) to update our submodule for wil and it's [failing to build](https://github.com/microsoft/xdp-for-windows/runs/8281952556?check_suite_focus=true) because of #257:
```
Build FAILED.

       "D:\a\xdp-for-windows\xdp-for-windows\xdp.sln" (default target) (1) ->
       "D:\a\xdp-for-windows\xdp-for-windows\test\functional\lib\xdptests.vcxproj" (default target) (19) ->
       (RunNativeCodeAnalysis target) -> 
         D:\a\xdp-for-windows\xdp-for-windows\submodules\wil\include\wil\result_macros.h(1314): error C6387: 'Temp_value_#1642' could be '0':  this does not adhere to the specification for the function 'GetProcAddress'.  [D:\a\xdp-for-windows\xdp-for-windows\test\functional\lib\xdptests.vcxproj]
```
I'm not 100% sure why, but it doesn't like this line:
```c
pfnRtlDisownModuleHeapAllocation = reinterpret_cast<decltype(pfnRtlDisownModuleHeapAllocation)>(::GetProcAddress(::GetModuleHandleW(L"ntdll.dll"), "RtlDisownModuleHeapAllocation"));
```

**Comment by nibanks** [comment]
cc @mtfriesen

**Comment by jonwis** [comment]
The issue is that `GetModuleHandle("muffindoesnotexist.dll")` _can_ return nullptr if indeed the DLL does not exist. In this instance, ntdll.dll is a core part of the OS that will never not exist. The fix would be to split the code across two lines, like so:

```c++
if (auto ntdllModule = ::GetModuleHandleW(L"ntdll.dll"))
{
    pfnRtlDisownModuleHeapAllocation = reinterpret_cast<...>(::GetProcAddress(ntdllModule, ...);
}
```
