### ISSUE TITLE
Suggestion: Add tags for versions pushed to NuGet gallery

### ISSUE THREAD

**Issue by benhillis** [microsoft/wil#262]
I noticed that this repo doesn't currently have any releases / tags which makes it difficult to compare repo history to NuGet package version.  Suggestion is to tag builds when NuGet packages are pushed to: https://www.nuget.org/packages/Microsoft.Windows.ImplementationLibrary

Not critical, just a suggestion! Thanks!

**Comment by dunhor** [comment]
Good suggestion. I created a release off the most recent commit (since that correlates with the last nuget version).

If you'd like to see even further in the past, you can browse commit history for the message "Sync". Virtually all versions should correspond to one of those commits.
