### ISSUE TITLE
wil::zstring_view is not mentioned on the Wiki

### ISSUE THREAD

**Issue by CookiePLMonster** [microsoft/wil#267]
This specialization of `std::string_view` sounds extremely useful and lives in public headers, next to `wil::secure_allocator`,  and yet the Wiki doesn't mention it. This makes it easily missable to the extent where I have no clue for how long it's been present in WIL.

**Comment by CookiePLMonster** [comment]
@dunhor As far as I know, Wiki doesn't allow for pull requests, so I'll ask here - do you think this is enough for the Wiki? I slightly adapted the comments from `stl.h`. I would say this belongs best in [String helpers](https://github.com/microsoft/wil/wiki/String-helpers).

```
## wil::zstring\_view

When C++17 is available and `stl.h` is included, WIL provides this helper class.
A `zstring_view` is identical to a `std::string_view` except it is always null-terminated (unless empty).
* `zstring_view` can be used for storing string literals without "forgetting" the length or that it is null-terminated.
* A `zstring_view` can be converted implicitly to a `std::string_view` because it is always safe to use a null-terminated `string_view` as a plain string view.
* A `zstring_view` can be constructed from a `std::string` because the data in `std::string` is null-terminated.
```

***

## wil::zstring\_view

When C++17 is available and `stl.h` is included, WIL provides this helper class.
A `zstring_view` is identical to a `std::string_view` except it is always null-terminated (unless empty).
* `zstring_view` can be used for storing string literals without "forgetting" the length or that it is null-terminated.
* A `zstring_view` can be converted implicitly to a `std::string_view` because it is always safe to use a null-terminated `string_view` as a plain string view.
* A `zstring_view` can be constructed from a `std::string` because the data in `std::string` is null-terminated.

**Comment by ChrisGuzak** [comment]
@CookiePLMonster go ahead with that edit. If you don't have permission let me know and I'll make that for you.

**Comment by CookiePLMonster** [comment]
@ChrisGuzak I was able to submit the edit: https://github.com/microsoft/wil/wiki/String-helpers/_compare/83c0d207cdafcf80da0231993298520ed07b633d...2dae3f2d035001e23bf03dbc0a2a418b4056af72

Thank you!
