### ISSUE TITLE
All previous releases and tags are gone

### ISSUE THREAD

**Issue by DHowett** [microsoft/wil#268]
I was considering updating Windows Terminal from the 2201 package to 2209, but the lack of tags and releases makes that somewhat impossible. Was this intentional? Can it be fixed?

**Comment by dunhor** [comment]
I'm not familiar with that package naming scheme. How are you consuming WIL?

**Comment by DHowett** [comment]
Sorry, I was using a (not agreed-upon in advance) shorthand. I was referring to `1.0.220201.1` and `1.0.220914.1` by their embedded year and month.

**Comment by dunhor** [comment]
I assume that's the nuget package? What's the issue here?

**Comment by DHowett** [comment]
Yes, the NuGet package. I'm reporting that there are no tags on this repository, nor releases on the [releases page](https://github.com/microsoft/wil/releases), for historical releases.

<img width="901" alt="image" src="https://user-images.githubusercontent.com/189190/195698092-28891a7e-d647-4d52-bbe3-4f4bd3c00ef6.png">
<img width="357" alt="image" src="https://user-images.githubusercontent.com/189190/195698113-f8d25335-8592-4ab8-a57c-21d574ac495f.png">

This leaves consumers no point of reference for an older release such as a commit ID that can be mapped to a version, for example to audit the changes between that version and another newer version.

Contrast cppwinrt, cpprestsdk, etc:

<img width="142" alt="image" src="https://user-images.githubusercontent.com/189190/195698426-565af922-627b-476e-9983-9e5834cda05a.png">

_cppwinrt_

--

The presence and veracity of tags pointing to earlier versions is important for a maintainable SBOM, especially among people who are not consuming WIL via a package manager. I must have misremembered that they used to exist on this repository! :smile:

**Comment by dunhor** [comment]
WIL has no "official" releases. It's more of a "live at head" philosophy (though the periodic nuget releases muddy that a bit). Prior to the most recent nuget package, no releases/tags have been created. We did start this recently (the one release you pointed to), which does contain the commit used. This is still mostly a lie as it only accounts for nuget.

**Comment by DHowett** [comment]
Ah, that makes sense. Thanks! 🙂
