### ISSUE TITLE
Possible out-of-bounds access in zstring_view.

### ISSUE THREAD

**Issue by DeirhX** [microsoft/wil#271]
Hi, I'm interested in your take on 
```
        template<size_t stringArrayLength>
        constexpr basic_zstring_view(const TChar(&stringArray)[stringArrayLength]) noexcept
            : std::basic_string_view<TChar>(&stringArray[0])
        {
            if (stringArrayLength < this->size()) { WI_STL_FAIL_FAST_IF(true); }
        }
```
Whenever the user is passing in a static buffer with a known length, he pretty much declares that he doesn't own any memory following the end of this buffer. However, this implementation discards the size information and passes a pointer to it to string_view's constructor which will then walk as far as needed to discover first nul terminator. In case it was not part of the buffer, it will walk through potentially unowned memory and stop only on its occurrence, potentially causing access violation. 

Wouldn't it be safer to prevent this undefined behavior by simply testing the last character of the buffer to be nul? The current approach also contains false positives - if you have a buffer without nul but happens to be directly followed by a nul from a completely different allocation, it will pass this condition (imho should have been `<= this->size()`). But once the owner of the nul decided to deallocate it, you can get a run-time access violation on using this zstring_view since it relies on the deallocated nul to be present (or worse - upon passing to LPCSTR accepting WinAPI function, it will read garbage until next nul in memory).

**Comment by CookiePLMonster** [comment]
The issue seems to be more along the lines of - what should happen if `basic_zstring_view` is constructed from malformed data? By definition, zstring should be null terminated and therefore there is an implication that somewhere in the passed array a null terminator exists and it's not going away.

Seems like the real fix here would be to use `strnlen` and pass data+size to the parent constructor, followed by a check already present in the codebase. You're most likely right about that check needing `<=` too.

**Comment by CookiePLMonster** [comment]
One major annoyance here is that `char_traits::length()` does not have an overload taking a buffer size/max length. This might need to be implemented "manually".

**Comment by CookiePLMonster** [comment]
A test for this case already exists:
https://github.com/microsoft/wil/blob/5eb59d60e167482639cc47ffb40442158da7fd04/tests/StlTests.cpp#L106-L108
But seems to me like it's getting "lucky" that the fastfail fires instead of triggering an exception due to an out of bounds read.

**Comment by CookiePLMonster** [comment]
Created https://github.com/microsoft/wil/pull/273 to try and resolve this issue.
