### ISSUE TITLE
Compilation issue with VS2017

### ISSUE THREAD

**Issue by j-schultz** [microsoft/wil#272]
When trying to include WIL headers in a VS2017 project, I get this compile error:

```
1>...\wil\resource.h(2550): error C2440: 'specialization': cannot convert from 'void (__cdecl *)(HANDLE) noexcept' to 'unknown-type'
1>...\wil\resource.h(2550): note: Context does not allow for disambiguation of overloaded function
```

Is VS2017 still officially supported? If not, what's the last officially supported version / commit?

I discovered this issue while trying to adapt this [sample code](https://learn.microsoft.com/en-us/samples/microsoft/windows-classic-samples/applicationloopbackaudio-sample/) provided by Microsoft to the latest WIL version. The sample pins version 1.0.210204.1 of WIL, obtained via NuGet, and the sample compiles without issues when using that version. Upgrading to the latest WIL master commit (8850b0352771b40a9f9d786c6b9280abe7f9a50b at the time of writing), however, breaks compilation.

**Comment by j-schultz** [comment]
Note to self: The commit that broke compilation is 5ea390f863512848b78cb2cbbe2dccb28c87400a, e3c16a8bef9cd89dcb68592cfbb796a7509d9a33 still works with VS2017. As this appears to be the only thing breaking VS2017 support, I wonder if it can be implemented in a different way that would still work for VS2017 (or at least conditionally excluded when that compiler is detected).

**Comment by dunhor** [comment]
I'm curious if this is related to the function pointer being declared as `noexcept`. There was a bug introduced into the compiler a while ago where the C++17 "`noexcept` in the type system" change "leaked" into building as C++14. If you update the project to build as C++17 does the error go away? If so, there was a macro introduced a while ago for this exact bug - `WI_PFN_NOEXCEPT` - that conditionally declares the pointer-to-function as `noexcept` depending on the target C++ language version. If so, we'd need to update to not use `decltype` and instead write out the pointer-to-function type explicitly using this macro.

**Comment by j-schultz** [comment]
That was one of the first things I tried, unfortunately the error also occurs when compiling as C++17.

**Comment by dunhor** [comment]
Closing in favor of #302, which has more info at this point.
