### ISSUE TITLE
Consider adding no_switch await adapter for IAsyncInfo

### ISSUE THREAD

**Issue by benstevens48** [microsoft/wil#274]
*Originally posted on C++/WinRT [here](https://github.com/microsoft/cppwinrt/issues/1217#issuecomment-1289319275)*

As far as I can see (please correct me if I'm wrong) there is no equivalent of C#'s Task.ConfigureAwait(false) built-in to C++/WinRT when awaiting IAsyncInfo types. There is a sample of how to do it in the doc here https://learn.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/concurrency-2 (look for no_switch) and it's also in this 'The Old New Thing' blog post - https://devblogs.microsoft.com/oldnewthing/20191216-00/?p=103217. I wonder if it would be a good idea to add this to WIL? C# recommends that all libraries should use ConfigureAwait(false) (where it doesn't matter about running on the UI thread) and I assume that we should be doing the same in C++/WinRT so a no_switch await adapter ought to be widely used. (And any non-UI OS components not using it or an equivalent when awaiting IAsyncInfo should probably add it).

**Comment by jonwis** [comment]
Completed as https://github.com/microsoft/cppwinrt/issues/1355
