### ISSUE TITLE
`get_token_information` incorrectly handles memory allocation/deallocation

### ISSUE THREAD

**Issue by AlexBAV** [microsoft/wil#276]
https://github.com/microsoft/wil/blob/7faa90d7185c8617f73694c5382b21cf4ed05825/include/wil/token_helpers.h#L163-L179

Essentially, the function directly calls `operator new` to allocate a buffer of memory:

https://github.com/microsoft/wil/blob/7faa90d7185c8617f73694c5382b21cf4ed05825/include/wil/token_helpers.h#L172-L173

and later casts the returned pointer to some structure type `T` (like `TOKEN_USER`):

https://github.com/microsoft/wil/blob/7faa90d7185c8617f73694c5382b21cf4ed05825/include/wil/token_helpers.h#L176

and finally calls `delete ptr`, where `ptr` has type `T *` (like `TOKEN_USER *`).

https://github.com/microsoft/wil/blob/7faa90d7185c8617f73694c5382b21cf4ed05825/include/wil/wistd_memory.h#L281

This does not seem to be legitimate (however "seems to work").

This issue is also reported by ASAN in Visual Studio 2022 17.4.0.

**Comment by jonwis** [comment]
Agreed. It "works" in that everything boils down to heapalloc/heapfree.  Somebody with a custom allocator or a tracking allocator would Sadly this is going to be a hard change to land. I'll need to change the return/output types to be a `wil::unique_token_info<T>` that is-a `wistd::unique_ptr<T, TokenInfoDeleter>` instead. Probably should have been that way from the get-go. @dunhor this is likely going to be a large impact to ingestion into the OS repo.

**Comment by dunhor** [comment]
Agree on the solution. The tricky ones will be `get_token_information_nothrow` and `get_token_information_failfast` as the caller needs to explicitly declare the result's type as it is an output parameter. I.e. uses of these _will_ need source changes. Searching for these two yields 76 files - let's call it 70 when we account for WIL itself and its tests. That's a lot, but not the worst we've ever had to go in and change. There's also hits in 80 files for `get_token_information` and I'm unsure how many of them don't use `auto`, or store it as a member, or pass it as input to another function, or need to forward declare outside of lock scope, etc.

It's typically better and more preferrable if these types of changes are made directly in the OS source code.

**Comment by dunhor** [comment]
Now I'm curious if I misunderstood the warning/error that led to me adding [this](https://github.com/microsoft/wil/blob/3e2ee372dcbbe77977934fbe0c58ff8ceb0236ee/tests/main.cpp#L17) when enabling the ASan/UBSan tests...

**Comment by jonwis** [comment]
Agree - "overallocate" is not the same as "mismatched allocator/freer" ... for the token case, it's reasonable to overallocate a chunk of memory so that a `struct SHOUTY_TYPE { DWORD x; ULONG_PTR yvals[1]; };` has enough space to store "x" yvals. But if that allocator called `HeapAlloc` but passed it to a unique_ptr that calls delete, that's the problem we want to avoid.

**Comment by jonwis** [comment]
For folks playing along from home, http://task.ms/43619989 is the OS work item.
