### ISSUE TITLE
Create a `wil::resume_background` coroutine that can cap the number of threads at a reasonable number

### ISSUE THREAD

**Issue by dmachaj** [microsoft/wil#293]
[winrt::resume_background](https://learn.microsoft.com/en-us/uwp/cpp-ref-for-winrt/resume-background) is the current state of the art for coroutines, background threads, and Windows programming.  As I understand it, cppwinrt would like to get out of the coroutine business and WIL is happy to fill this role.  See `wil::resume_foreground`.

One problem with `winrt::resume_background` is that it is unbounded for thread usage.  It will happily request lots and lots of threads if you schedule a bunch of calls all at once.  Once these threads reach a high enough number it becomes self-defeating and slows things down instead of making it faster.

It should be possible to use threadpool APIs such as [SetThreadpoolCallbackPool](https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-setthreadpoolcallbackpool) to correlate these "background" coroutine calls with the Windows threadpool.  This would allow the number of threads to be capped.

Those APIs seem like they would be difficult to use, and to use correctly.  That means that a well-tested implementation in WIL would be valuable.

Having not thought deeply about exactly how this would look, what I have in mind is something like:

```cpp
winrt::fire_and_forget DoThingAsync()
{
    co_await wil::resume_foreground(4); // will never use more than 4 background threads, including other calls in other functions
    // other code that runs on a background thread
    co_return;
}
```

**Comment by dmachaj** [comment]
I think a reasonable test case for this would be:

```cpp
std::unordered_set<DWORD> backgroundThreads;
for (auto i = 0; i < 100; ++i)
{
  co_await wil::resume_background(4);
  backgroundThreads.emplace(GetCurrentThreadId());
}
// wait on all coroutines to have run
VERIFY(backgroundThreads.count() == 4); // may need a fudge factor if the number of threads never exceeds 4 but more than 4 different threads are ever used by the threadpool
```

**Comment by dmachaj** [comment]
Thanks @kennykerr for pointing out [winrt::thread_pool](https://github.com/microsoft/cppwinrt/blob/b5503ee594cbd01f911c222f9367d327cb885bf8/strings/base_coroutine_threadpool.h#L599-L628) which may satisfy this desire.

Usage seems to be roughly:
```cpp
winrt::thread_pool myPool;
myPool.thread_limits(4, 1);

// elsewhere
co_await myPool;
```

**Comment by jonwis** [comment]
> Thanks @kennykerr for pointing out [winrt::thread_pool](https://github.com/microsoft/cppwinrt/blob/b5503ee594cbd01f911c222f9367d327cb885bf8/strings/base_coroutine_threadpool.h#L599-L628) which may satisfy this desire.
> 
> Usage seems to be roughly:
> 
> ```c++
> winrt::thread_pool myPool;
> myPool.thread_limits(4, 1);
> 
> // elsewhere
> co_await myPool;
> ```

@dmachaj Is this sufficient for your needs? It's a little odd that I have to go grab cppwinrt to use a threadpool coroutine, but maybe that's OK? The alternative is to port the cppwinrt thread_pool into WIL and provide additional convenience wrappers over it, like things that create lambda-based callbacks, in the same vein as the registry/file/etc watchers.

**Comment by kennykerr** [comment]
Yes, it's not specific to WinRT and would be more appropriate in a library such as this - much like @oldnewthing's other coroutine helpers.

**Comment by dmachaj** [comment]
This is unblocked for now so I'm going to close this out.  If someone wants to port the helpers over to WIL later then they can reactivate this issue.
