### ISSUE TITLE
Is it possible to do `auto handle = RETURN_LAST_ERROR_IF_NULL(GetXxxHandle())` in one line? 

### ISSUE THREAD

**Issue by GF-Huang** [microsoft/wil#294]
Now, I must split it into two lines.

```c++
auto handle = GetXxxHandle();
RETURN_LAST_ERROR_IF_NULL(handle);
```

**Comment by talagrand** [comment]
Unfortunately not - "return" is a statement, and statements can't appear inside an expression.
Unless you want to [get crazy](https://cpp-rendering.io/c-error-handling-lets-abuse-the-co_await-operator/)

**Comment by dunhor** [comment]
Correct. You can't both have a `return` expression in a statement _and_ have that statement evaluate to a value
