### ISSUE TITLE
Why `RETURN_LAST_ERROR_IF_NULL_EXPECTED` only accepts 1 argument? How to set expected last errors?

### ISSUE THREAD

**Issue by GF-Huang** [microsoft/wil#295]
![image](https://user-images.githubusercontent.com/4510984/215313821-b3473efc-77e7-475a-9dca-49e5186c5557.png)

**Comment by talagrand** [comment]
The *_EXPECTED macros do not filter out certain errors, they say that ALL errors from this call should not be logged.
If you'd like to ignore specific errors, see here: https://devblogs.microsoft.com/oldnewthing/20220414-00/?p=106483

**Comment by dunhor** [comment]
While it's true that something like `RETURN_LAST_ERROR_IF_NULL_EXPECTED` has only one "variant" that doesn't log _any_ errors, there are a couple `_WITH_EXPECTED` macros (e.g. `RETURN_IF_FAILED_WITH_EXPECTED`) that allow a list of specific errors to ignore. I'm guessing that something like `RETURN_LAST_ERROR_IF_NULL_WITH_EXPECTED` lacks enough use cases to have been added.

**Comment by GF-Huang** [comment]
@dunhor  Consider if you want to call [`DeleteService`](https://learn.microsoft.com/en-us/windows/win32/api/winsvc/nf-winsvc-deleteservice) to delete a service whether it exists or not. If the `service` does not exists, it will return `FALSE`, and `GetLastError()` return `ERROR_SERVICE_DOES_NOT_EXIST`. In this case, should be ignore the `ERROR_SERVICE_DOES_NOT_EXIST` and treat as  success.
