### ISSUE TITLE
VS2017 noexcept-in-typesystem bug is hitting with the definition of 'unique_private_namespace'

### ISSUE THREAD

**Issue by iamtcby5188** [microsoft/wil#302]
1>wb2.cpp
1>e:\code\mytest\wb2\packages\microsoft.windows.implementationlibrary.1.0.230202.1\include\wil\resource.h(2550): error C2440: “specialization”: 无法从“void (__stdcall *)(HANDLE) noexcept”转换为“unknown-type”
1>e:\code\mytest\wb2\packages\microsoft.windows.implementationlibrary.1.0.230202.1\include\wil\resource.h(2550): note: 上下文不允许消除重载函数的歧义

**Comment by dunhor** [comment]
What does your code look like that causes this error?

**Comment by dunhor** [comment]
Also, since this appears to maybe be related to `noexcept` in the type system, what compiler/version are you using and what C++ version are you compiling against?

**Comment by jimmyleocn** [comment]
same error here.

**Comment by dunhor** [comment]
If memory serves me correctly, VS2017 has a behavior where it'll ignore `noexcept` declared on a function pointer, but not ignore it in `decltype` (or the other way around; it's been a while). If you compile with `/std:c++17`, does the error persist?

**Comment by dunhor** [comment]
If that _is_ the issue, then we could go about it by explicitly writing the type instead of using `decltype` as we've done in the past before.
```c++
    template <ULONG flags = 0>
    using unique_private_namespace = unique_any_handle_null_only<void(__stdcall*)(HANDLE) WI_PFN_NOEXCEPT, &details::ClosePrivateNamespaceHelper<flags>>;
```

**Comment by icnocop** [comment]
See https://github.com/microsoft/wil/issues/272

**Comment by icnocop** [comment]
> If you compile with `/std:c++17`, does the error persist?

In my case, compiling with `/std:c++17` did not resolve the issue.

Windows SDK Version: 10.0.14393.0
Platform Toolset: Visual Studio 2017 (v141)
Configuration Type: Application (.exe)
Use of MFC: Use MFC in a Shared DLL
Character Set: Use Unicode Character Set

Microsoft.Windows.ImplementationLibrary 1.0.230202.1
Microsoft.Web.WebView2 1.0.1661.34

```
.\packages\microsoft.windows.implementationlibrary.1.0.230202.1\include\wil\resource.h(2550): error C2440: 'specialization': cannot convert from 'void (__cdecl *)(HANDLE) noexcept' to 'unknown-type'
.\packages\microsoft.windows.implementationlibrary.1.0.230202.1\include\wil\resource.h(2550): note: Context does not allow for disambiguation of overloaded function
```

**Comment by dunhor** [comment]
Sounds like from my comment in #25, it was VS _2019_ that had the `noexcept` pointer-to-function issue, not 2017. Perhaps 2017 is just even more broken... Can anyone hitting this check to see if the code I pasted above helps or not?

**Comment by icnocop** [comment]
Yes, replacing 

```
    template <ULONG flags = 0>
    using unique_private_namespace = unique_any_handle_null_only<decltype(details::ClosePrivateNamespaceHelper<flags>), &details::ClosePrivateNamespaceHelper<flags>>;
```
with
```
template <ULONG flags = 0>
    using unique_private_namespace = unique_any_handle_null_only<void(__stdcall*)(HANDLE) WI_PFN_NOEXCEPT, &details::ClosePrivateNamespaceHelper<flags>>;
```
allows the code to compile. 

As another work-around, downgrade the NuGet package Microsoft.Windows.ImplementationLibrary to 1.0.210803.1.

Thank you.
