### ISSUE TITLE
VS2019 default build fails

### ISSUE THREAD

**Issue by tiagomacarios** [microsoft/wil#32]
(See vcsig email thread)

If you try to build wil with Visual Studio (File > Open >Cmake) using VS2019 (16.1.0 Preview 3.0) it will fail with:
wil\tests\wiTest.cpp(117): warning C4244: 'initializing': conversion from 'long' to 'unsigned short', possible loss of data

This is the line where the error occurs:
unsigned short errorLine = __LINE__;

__LINE__ has different types in different contexts when compiled with ZI thus the error. The docs mention that it is not a constant, but there is no mention that the type also changes.

https://godbolt.org/z/DlOqtV
https://github.com/MicrosoftDocs/cpp-docs/issues/1002

The modified CMake version shipped with VS2019 changed the default compiler flag from Zi ot Zi. See here: https://github.com/microsoft/CMake/pull/75

**Comment by ChrisGuzak** [comment]
perhaps using auto here will help. 

        LOG_HR(E_FAIL); auto errorLine = __LINE__;

but that might require more changes given this type propagates to other types. the other option is static_cast<decltype(errorLine)>(__LINE__).

can you give that a try?

This is probably the same as wil does not work with the compliant pre-processor

**Comment by jonwis** [comment]
This is being fixed in PR #51

**Comment by dunhor** [comment]
Closing since #51 has been merged
