### ISSUE TITLE
wil::reg functions need an enumeration function to walk values and keys

### ISSUE THREAD

**Issue by keith-horton** [microsoft/wil#338]
Feature Request: need to add functions to enumerate values and keys which return an object that supports iterator semantics for ranged-for loops and algorithms, as well as supporting ranges.

e.g., walking dword values under a registry key:

for (const auto& value_name : wil::reg::enumerate_values(key)
{
    auto value = wil::reg::get_value_dword(key, value_name);
}

**Comment by ChrisGuzak** [comment]
and 
```cpp
for (auto&& [key, value] : wil::reg::enumerate_names_and_values(key)
{

}
```

**Comment by ChrisGuzak** [comment]
here was [my first](https://dev.azure.com/chrisguzak/Projects/_search?action=contents&text=registry_key_range&type=code&lp=code-Project&filters=ProjectFilters%7BProjects%7DRepositoryFilters%7BChrisGuzakWork%7D&pageSize=25&result=DefaultCollection/Projects/ChrisGuzakWork/GBmaster//Laboratory/RegistryHelpersProposal.h) run at this. I'm sure it needs improvements.

**Comment by keith-horton** [comment]
We had a tested implementation earlier - it was removed as folks requested the initial commit be much simpler.
[wil_iterator.txt](https://github.com/microsoft/wil/files/11889773/wil_iterator.txt)
