### ISSUE TITLE
warning C6001

### ISSUE THREAD

**Issue by kouzhudong** [microsoft/wil#347]
packages\Microsoft.Windows.ImplementationLibrary.1.0.230629.1\include\wil\resource.h(5599): warning C6001: 使用未初始化的内存“*hClientHandle”。

**Comment by dunhor** [comment]
Analyzer is complaining here:
```c++
        inline void __stdcall CloseWlanHandle(_Frees_ptr_ HANDLE hClientHandle)
        {
            ::WlanCloseHandle(hClientHandle, nullptr);  // <======== HERE
        }
```
Not so sure that `_Frees_ptr_` is the correct annotation
