### ISSUE TITLE
`single_threaded_property` should not be externally writeable

### ISSUE THREAD

**Issue by citelao** [microsoft/wil#353]
`single_threaded_property` is intended for readonly properties (`{ get; };`). `single_threaded_rw_property` should be used for settable properties (`{ get; set; };`).

However, the current implementation of `single_threaded_property` can be used for settable properties because it contains `operator()(T&&)`.

The fix is to remove that overload.

**Comment by dunhor** [comment]
This is also fixed now, right?

**Comment by citelao** [comment]
No, I'm looking into this now.

**Comment by citelao** [comment]
Fixed by #366

**Comment by jonwis** [comment]
Fixed in #366, thanks!
