### ISSUE TITLE
std::invoke for callables.

### ISSUE THREAD

**Issue by sylveon** [microsoft/wil#36]
C++17 allows some pretty crazy things with templates. Observe the following:

```cpp
template <typename T>
struct member_parent { };

template<typename Object, typename Return, typename... Args>
struct member_parent<Return(Object:: *)(Args...)> {
	typedef Object type;
};

template<typename T>
using member_parent_t = typename member_parent<T>::type;

template<auto close_fn, typename token_t, token_t invalid_token = token_t()>
using com_token = wil::unique_com_token<member_parent_t<decltype(close_fn)>, token_t, decltype(close_fn), close_fn, invalid_token>;
```

This code allows to simplify writing a custom COM token:
```cpp
using app_visibility_sink_cookie = com_token<&IAppVisibility::Unadvise, DWORD>;
```

However, it can't be easily included in wil without depending on C++17 (we can't overload templated type aliases, C++ determined that would be too easy).

The code should work, but doesn't, because of this line: https://github.com/microsoft/wil/blob/ade910fb44f0b23c03111a2838c2148d326f5622/include/wil/resource.h#L1370

If that line where to be changed to `std::invoke(close_fn, m_source, m_token);`, this would work. However, I am aware that wil tries to avoid dependencies on the system standard library, and I am honestly unsure on how I would proceed to add more stuff to `wistd`.

Ideally, replacing all of the calls of function pointer template parameters like above by calls to `wistd::invoke` would allow more creativity in the use of wil.

**Comment by sylveon** [comment]
```cpp
#pragma once
#include <cstddef>
#include <tuple>
#include <wil/resource.h>

namespace wilx {
	// Send help
	namespace impl {
		template <typename T>
		struct member_function_traits { };

		template<typename Parent, typename Return, typename... Args>
		struct member_function_traits<Return(Parent:: *)(Args...)> {
			using parent = Parent;

			template<std::size_t i>
			using arg = std::tuple_element_t<i, std::tuple<Args...>>;
		};

		template<typename T>
		using member_parent_t = typename member_function_traits<T>::parent;

		template<typename T, std::size_t i>
		using member_arg_t = typename member_function_traits<T>::arg<i>;
	}

	template<auto close_fn, impl::member_arg_t<decltype(close_fn), 0> invalid_token = impl::member_arg_t<decltype(close_fn), 0>()>
	using unique_com_token = wil::unique_com_token<impl::member_parent_t<decltype(close_fn)>, impl::member_arg_t<decltype(close_fn), 0>, decltype(close_fn), close_fn, invalid_token>;

	template<auto close_fn>
	using unique_com_call = wil::unique_com_call<impl::member_parent_t<decltype(close_fn)>, decltype(close_fn), close_fn>;
}
```

It gets worse (or better, depends on how you look at it)

**Comment by dunhor** [comment]
Can't you already effectively achieve this?
```c++
template <typename CloseFnT, CloseFnT CloseFn>
struct unique_com_token_member_function_traits;

template <typename Return, typename T, typename Token, Return(T::*CloseFn)(Token)>
struct unique_com_token_member_function_traits<Return(T::*)(Token), CloseFn>
{
    static Return close(T* ptr, Token tok)
    {
        return (ptr->*CloseFn)(tok);
    }

    using type = wil::unique_com_token<T, Token, decltype(&close), &close>;
};

template <auto CloseFn>
using unique_com_token = typename unique_com_token_member_function_traits<decltype(CloseFn), CloseFn>::type;
```

**Comment by dunhor** [comment]
Though, of course it needs a `STDMETHODCALLTYPE` calling convention since this is COM we're talking about

**Comment by sylveon** [comment]
I seriously overthought this. While that works, I guess my solution does have the advantage of also working with `unique_com_call` without much additional effort, and still allowing to (optionally) manually specify the `invalid_token`, which is where a solution like this seems to have trouble with.

Nonetheless, I still think `std::invoke` should be used to invoke callables, because otherwise it won't handle simplier situations like this one (which is basically what my template mess expands to):
```cpp
wil::unique_com_token<IAppVisibility, DWORD, decltype(&IAppVisibility::Unadvise), &IAppVisibility::Unadvise>
```
```
