### ISSUE TITLE
unique_mutex : can't find how you pair closehandle on mutex in WIL

### ISSUE THREAD

**Issue by eriksac** [microsoft/wil#380]
In MSDN OpenMutexW function Remarks, I read "The system closes the handle automatically when the process terminates. The mutex object is destroyed when its last handle has been closed."

Does WIL closehandle on reset, on release ... ? can't find any reference in resource.h

**Comment by sylveon** [comment]
> Move-assignment like m_h = std::move(h)

Note that this closes the handle in `m_h`, not `h`

**Comment by jonwis** [comment]
See also the docs on the wiki for `wil::unique_handle` and friends. https://github.com/microsoft/wil/wiki/RAII-resource-wrappers#available-unique_any-handle-types
