### ISSUE TITLE
Add a "resume background queue" mechanism

### ISSUE THREAD

**Issue by jonwis** [microsoft/wil#388]
This XAML code is problematic:

```c++
winrt::fire_and_forget Foo::Bar_Clicked(auto...) {
    auto lifetime{get_strong()};
    winrt::apartment_context ui_thread;
    co_await winrt::resume_background();
    // Do expensive stuff computing a new value
    co_await ui_thread;
    TextBox1().Text(theNewlyComputedValue);
}
```

If the user clicks the button quickly, while each "click" is serialized on the dispatcher for the UI element, the `co_await background` switches off that serialized queue to start work. There's a few workarounds, for "first one wins":

```c++
// Disable the element visually
winrt::fire_and_forget Foo::Bar_Clicked(auto...) {
    auto lifetime{get_strong());
    Bar().Enabled(false); // Don't allow more clicks
    // as above, except at the end...
    Bar().Enabled(true); // re-enable the button
}

// Use a ticket or token indicating that it's already running
winrt::fire_and_forget Foo::Bar_Clicked(auto...) {
    auto lifetime{get_strong());
    if (m_costlyThingRunning) {
        co_return;
    } else {
        m_costlyThingRunning = true; // std::atomic<bool> m_costlyThingRunning;
    }
    // as above, except at the end...
    m_costlyThingRunning = false; // Next click in the UI can happen
}
```

... and there are more expensive operations for "cancel the running one and restart" or "at most queue two; one running and one 'refresh' if the button's clicked more than once."  And of course, the code could create its own `Dispatcher` to queue background work, and use `co_await m_backgroundDispatcher;` instead of `co_await resume_background()`.

It'd be nice if there was a construct to make this integrate directly with `co_await` so we can write this:

```c++
winrt::fire_and_forget Foo::Bar_Clicked(auto...) {
    auto lifetime{get_strong()};
    auto priorContext = co_await m_background();
    // Do expensive work
    co_await priorContext;
    TextBox1().Text(theNewlyComputedValue);     
}
```

Where the `m_background` is some sort of queueing system with a few potential properties:

* Reuses the same background thread as much as possible (ie: fully drains queued work before returning)
* Strict FIFO queue of work
* Option to limit queue depth by some kind of ID.  "If id-x is running, queue at most one more run of id-x"

This may require some clever management of "I'm still running on this bg thread" ticket management. Something needs to tell the `m_background` tracker "OK, I'm done with running this chunk, release the next one."

**Comment by dmachaj** [comment]
This seems to have some overlap with #293.  [winrt::thread_pool](https://github.com/microsoft/cppwinrt/blob/b5503ee594cbd01f911c222f9367d327cb885bf8/strings/base_coroutine_threadpool.h#L599-L628) with (1,1) as the arguments would serialize the background onto a single threadpool thread.  (Although you'd maybe want to share threadpools across functions so you don't spawn a ton of distinct threadpools).

**Comment by jonwis** [comment]
True - threadpool instances are _generally_ cheap; the kernel TP manager just has a list of available threads and assigns them to pools as necessary. You don't get a specific "TID 325 is only part of Pool 4" - you get "TID 325 is a TP thread waiting for work" and "Pool 4 gets at most one thread executing at a a time."  I'd forgotten that got implemented, so maybe that's a good way to mock up the work to start with.

**Comment by jonwis** [comment]
Oop - I just noticed that wil::thread_pool uses the "set minimum amount" which IIRC does a hard reservation so the pool is never starved by other pools. So I'd probably want a (0, 1) then.

**Comment by jonwis** [comment]
Yeah, I think that works for me. So it'd be like:

```c++
struct MyButton : MyButtonT<MyButton> {
    winrt::fire_and_forget OnClick(auto&& sender, auto&& args) {
        // starting out on the dispatcher queue for the button
        auto lifetime{get_strong()};
        winrt::apartment_context ui_thread;
        co_await m_background;
        // exclusive threading operation here for this one button, not globally
        co_await ui_thread;
        // Back on the dispatcher queue thread for the button
    }
private:
    winrt::thread_pool m_background(1, 0); // max one thread, min zero
};
```

... and then we can figure out how to make the "ticket taker" model work on top of that so we can apply "first one wins" or "first and at most one more wins" models.
