### ISSUE TITLE
wil::unique_any specialization suitable for CommandLineToArgvW

### ISSUE THREAD

**Issue by CookiePLMonster** [microsoft/wil#394]
At the moment, using a WIL unique_ptr-like buffer with [CommandLineToArgvW](https://learn.microsoft.com/windows/win32/api/shellapi/nf-shellapi-commandlinetoargvw) requires typing out the type manually:
```cpp
wil::unique_any<PWSTR*, decltype(&::LocalFree), ::LocalFree> args { CommandLineToArgvW(GetCommandLineW(), &numArgs) };
```

Considering the existence of `typedef unique_any<PWSTR, decltype(&::LocalFree), ::LocalFree> unique_hlocal_string;`, this variation could likely be defined as `wil::unique_hlocal_string_array`? It might also **not** need a `make_` function as far as I can tell.

Alternately, perhaps there should be `wil::CommandLineToArgvW` that returns a span type that is a combination of the above `wil::unique_any` and a size parameter? Are there any instances of WIL doing something like this already? Something like:

```
struct ArgcArgv
{
   PWSTR* argv;
   int argc;
};
```

with a destructor calling `::LocalFree` on `argv`. This struct is easily small enough that it could be returned from `wil::CommandLineToArgvW` by value. Another additional benefit of this approach is easier access to `argv`- the `unique_any` approach requires accessing the array via `args.get()[n]`, while the structure approach would be accessed via `args.argv[n]`.

**Comment by dunhor** [comment]
Wouldn't it be fine to just use `wil::unique_hlocal_ptr<PWSTR[]>` for the type? You'd even get a definition for `operator[]` as well

**Comment by dunhor** [comment]
In general, the `_ptr` aliases are just wrappers around `(wi)std::unique_ptr` and therefore get the same single deleter call. You'd have to use something like `unique_any_array_ptr` for it to apply a deleter to every element.

I'll close for now; re-open if you run into issues.
