### ISSUE TITLE
WI_FAIL_FAST_ASSERT missing semicolon

### ISSUE THREAD

**Issue by Codorono** [microsoft/wil#431]
This line:
WI_FAIL_FAST_ASSERT(::GetTickCount64() == 0);

Gives this error:
error C2143: syntax error: missing ';' before '}'

Because this line:
__RFF_FN(FailFast_Unexpected)(__RFF_INFO_ONLY(#condition)) \

Should have a semicolon:
__RFF_FN(FailFast_Unexpected)(__RFF_INFO_ONLY(#condition)); \

**Comment by dunhor** [comment]
Thanks for reporting this
