### ISSUE TITLE
wil/winrt.h requires time.h to be included to use it

### ISSUE THREAD

**Issue by ChrisGuzak** [microsoft/wil#44]
Raymond pointed this out here: https://github.com/microsoft/wil/wiki/Windows-Runtime-helpers

this should be fixed.

**Comment by jonwis** [comment]
It's missing `#include <windows.foundation.h>` which has the definition for Windows::Foundation::DateTime.  It already includes `windows.foundation.collections.h` so it's a short hop to adding it.
