### ISSUE TITLE
key_iterator_data string corruption

### ISSUE THREAD

**Issue by HO-COOH** [microsoft/wil#441]
I was using this code to enumerating registry subkeys and use the `.name` member to concat strings to get subkey values
```cpp
for (auto& key : wil::make_range(wil::reg::key_iterator{ hParentKey.get() }, wil::reg::key_iterator{}))
{
    ....
    auto value = wil::reg::try_get_value_string(..., parentKey + key.name, ...
}
```
Then I found out the parameter `parentKey + key.name` passed to `try_get_value_string` is getting trimmed. Looking at the `key.name` member, the string's `size` is wrong.
![image](https://github.com/microsoft/wil/assets/42881734/125845d3-e033-4451-a2cf-adffba515a3d)

**Comment by dunhor** [comment]
What "release" of WIL are you using? @ChrisGuzak does this look like the same issue that you reported a while ago that was later fixed?

**Comment by HO-COOH** [comment]
Confirmed. I was using this release that has the issue (this might be the version coming from the winui3 C++ project template or whatever)
![image](https://github.com/microsoft/wil/assets/42881734/c28bbe14-a165-430a-88ce-ba5efda65726)

Upgrading to 
![image](https://github.com/microsoft/wil/assets/42881734/d0e80ec4-0900-47d0-b550-eae5f198283d)
 solves the issue
