### ISSUE TITLE
CreateFileW helpers are marked noexcept but throw

### ISSUE THREAD

**Issue by ast-project-nd** [microsoft/wil#444]
The `CreateFileW` helpers in `filesystem.h` are marked `noexcept` but throw on error. This means that an error in any of these helpers will always cause `std::terminate` to be called. This affects the following functions:
- `open_file`
- `create_new_file`
- `open_or_create_file`
- `open_or_truncate_existing_file`
- `truncate_existing_file`

**Comment by dmachaj** [comment]
@ChrisGuzak this seems to be related to #382.  Can you please take a look when you are able?

**Comment by ChrisGuzak** [comment]
#445

**Comment by jonwis** [comment]
Completed.
