### ISSUE TITLE
WI_AreAllFlagsSet doesn't compile for C++/WinRT defined enum flags

### ISSUE THREAD

**Issue by mithrandir** [microsoft/wil#45]
If you want to deal with C++/WinRT's projected enum flags and using WI_AreAllFlagsSet, it doesn't compile. The reason is C++/WinRT defines its enum operator in global namespace but enum is defined in their own namespace. So ADL doesn't work, then WIL have several enum operators (for its own type) in `wil::details` or `wil` namespaces so it doesn't go hunting for global namespace.

The fix from WIL side would be stopping relying on enum operator and just cast it to underlying integral type, using WI_EnumValue, just like WI_IsAnyFlagSet does

**Comment by dunhor** [comment]
This is definitely a C++/WinRT issue as it breaks scenarios unrelated to WIL. E.g. the following does not compile:
```c++
namespace foo
{
    enum class values
    {
        first = 1,
        second = 2,
    };
}
DEFINE_ENUM_FLAG_OPERATORS(foo::values);

namespace bar
{
    enum class other_values
    {
        first = 1,
        second = 2,
    };
    DEFINE_ENUM_FLAG_OPERATORS(other_values);

    constexpr foo::values test = foo::values::first | foo::values::second;
}
```
That said, leaving this open for discussion as to whether or not this would be a good thing to do. My personal opinion is that no, we should not, however if `WI_IsAnyFlagSet` does it, there's certainly the possibility for a consistency argument.

**Comment by kennykerr** [comment]
Thanks for the repro Duncan!

**Comment by kennykerr** [comment]
This has been fixed in C++/WinRT.
