### ISSUE TITLE
BuildAndTest timeout should be shorter than 6 hours

### ISSUE THREAD

**Issue by dmachaj** [microsoft/wil#461]
Runs seem to take ~30 minutes so a 60-minute timeout would provide 2x overhead just in case.  The five additional hours of runtime is wasteful when something stops making progress.

See: https://github.com/microsoft/wil/blob/f0c6a81c0c9a4b23b6801f40554b8bec425a83b4/scripts/azure-pipelines.yml#L39

**Comment by dunhor** [comment]
For those curious, the pipeline used to be sequential meaning all binaries and tests were built/run on a single machine. At that time, a max timeout of 6 hours was pretty necessary. We have since parallelized the pipeline making this long of a timeout unnecessary. 60 min sounds like a good number.
