### ISSUE TITLE
com_timeout can leak an EnableCallCancellation

### ISSUE THREAD

**Issue by oldnewthing** [microsoft/wil#481]
The wil::com_timeout_t contains a leak if CreateThreadpoolTimer fails and we are in exception mode (i.e. wil::com_timeout).

https://github.com/microsoft/wil/blob/6f60a1b76fb812c6af5db1bc7abdec0001edd43f/include/wil/com.h#L3350-L3365

if CreateThreadpoolTimer fails, then we throw an exception out of the constructor. The rule in C++ is that if an exception is thrown by the constructor, then the destructor does not run. (You cannot destruct something that failed to construct.) This means that we never call CoDisableCallCancellation to counteract the CoEnableCallCancellation that occurred earlier in the constructor.

If an exception occurs in the constructor, we *do* run the destructors of member variables and base classes. So the obligation to call CoDisableCallCancellation should be held in a member variable.

```cpp
namespace details
{
    void CoDisableCallCancellationNull() { ::CoDisableCallCancellation(nullptr); }
}

struct com_timeout_t
{
private:
    wil::unique_call<decltype(details::CoDisableCallCancellationNull), details::CoDisableCallCancellationNull> m_ensureDisable(false); // <<<<
    wil::unique_threadpool_timer_nocancel m_timer;

public:
    com_timeout_t(DWORD timeoutInMilliseconds) : m_threadId(GetCurrentThreadId())
    {
        auto hr = CoEnableCallCancellation(nullptr);
        err_policy::HResult(hr);
        if (SUCCEEDED(hr))
        {
            m_ensureDisable.activate(); // <<<< remember to disable call cancellation at destruction
            m_timer.reset(CreateThreadpoolTimer(&com_timeout_t::timer_callback, this, nullptr));
            ... etc ...
        }
    }

    // not copyable or movable because the timer_callback receives "this"
    com_timeout_t(com_timeout_t const&) = delete;
    void operator=(com_timeout_t const&) = delete;
};
```

Removing the destructor activates the move constructor and move assignment operators, so we explicitly delete the copy constructor and copy assignment (which implicitly also delete the move constructor and move assignment).

**Comment by dmachaj** [comment]
@oldnewthing a fix is out for PR with #483.  I don't have permissions to directly add you to the PR.
