### ISSUE TITLE
Publish wil via conan dependency manger (https://conan.io)

### ISSUE THREAD

**Issue by p-groarke** [microsoft/wil#53]
Any chance you would publish on conan?

**Comment by ChrisGuzak** [comment]
I'll ask, what is conan? my searches did not find anything obvious.

**Comment by p-groarke** [comment]
Conan is a dependency manager. See https://bintray.com/conan/conan-center for the main repo of available packages. Their website : https://conan.io/

Good day

**Comment by kennykerr** [comment]
Conan is one of the leading package/dependency managers for C++ libraries.

**Comment by smaillet-ms** [comment]
@p-groarke 
I have to ask, what value conan adds to the table here. I'm not knocking conan in general, just not sure what the value of that is for **this** repo? the "W" in WIL is "Windows" everything in the library is VERY Windows OS specific so what value is there in having multiple packaging schemes? What scenario isn't possible with the existing Nuget Package that warrants the effort to create and maintain another packaging format? (and one not supported in VS as it prefers VCKG)

**Comment by SamuelEnglard** [comment]
@smaillet-ms The gain (for where I work at least) is that we're using CMake with Conan for cross-platform work. While WIL will only be used on Windows builds, we cannot (easily) use NuGet since CMake generates the VS projects.

**Comment by p-groarke** [comment]
This isn't necessary anymore since wil now supports cmake installation. Which means we can easily consume it through cmake directly (using your preferred method, ExternalDependency, FetchContent, global install, etc).

That MS wants to push its own competing products is to be expected and reasonable. Though passing off nuget as a c++ package manager is laughable ;)

**Comment by elejke** [comment]
@p-groarke https://github.com/conan-io/conan-center-index/pull/16701
