### ISSUE TITLE
RETURN_HR_MSG and "%s" failure

### ISSUE THREAD

**Issue by BeErikk** [microsoft/wil#55]
While doing a couple of case studies on how to use **wil**, I tested the following simple case which doesn't work for me

```
constexpr char failstr[] = "fail";
HRESULT FailingFunc(bool dofail)
{
	if (dofail)
		RETURN_HR_MSG(E_INVALIDARG, "%s is not a valid string", failstr);
	return E_INVALIDARG;
}
```
Outputs:
```
..\src\testwil.cpp(9)\wiltest.exe!00007FF7CD7016F7: (caller: 00007FF7CD70314F) ReturnHr(2) tid(11ca4) 80070057 Felaktig parameter.
    Msg:[?? is not a valid string] [FailingFunc(E_INVALIDARG)]
```

**Comment by BeErikk** [comment]
Right, the macro works if the variadic argument is a wide c-string. Like so:
`constexpr wchar_t failstr[] = L"fail";`
The format string, however, must be narrow. A bit odd perhaps?

**Comment by dunhor** [comment]
Correct. [Here is a link to the section of the wiki talking about this](https://github.com/microsoft/wil/wiki/Error-handling-helpers#using-custom-messages)

**Comment by BeErikk** [comment]
Thanks
