### ISSUE TITLE
GetEnvironmentStrings&FreeEnvironmentStrings memory management is missing

### ISSUE THREAD

**Issue by jeanga** [microsoft/wil#62]
Hello,

<wil\Resource.h> could have a unique_environment_ptr to handle the call to FreeEnvironmentStrings.

wil::unique_any could do it but a wil specialisation would help avoid mistakes and typing (which are goals of wil aren't they? :-) )
Thanks for the great library!
Jean

**Comment by sylveon** [comment]
If by typing you mean "mixing unique_any specializations", it's not possible because each specialization is a different type.

**Comment by jeanga** [comment]
I just meant keyboard presses :-)

**Comment by jonwis** [comment]
This could go in wil/win32_helpers.h:

```c++
    using unique_environstrings_ptr = unique_any<PWCH, decltype(&::FreeEnvironmentStringsW), ::FreeEnvironmentStringsW>;
```

And then:

```c++
    unique_environstrings_ptr e{ ::GetEnvironmentStringsW() };
    RETURN_LAST_ERROR_IF(!e);
```

**Comment by sylveon** [comment]
Isn't the `_ptr` suffix misleading if it is a unique_any specialization?

Any reason why win32_helpers.h over resource.h, where all the other unique_any specializations are?
