### ISSUE TITLE
Analysis warnings when more rules are enabled

### ISSUE THREAD

**Issue by jonwis** [microsoft/wil#67]
The project is _mostly_ clean when analyzed with the `NativeRecommenedRules.ruleset` ... Some projects enable additional checks (such as 6340 and 6322) for which the project is not as clean.

Specific examples:

* result_macros.h:1106 - warning C6340 - printf format specificer signedness mismatch
* result_macros.h:2961 - warning C6322 - empty except block

To resolve this issue, consider finding and adding the .ruleset file for that internal project.

**Comment by NoelCross** [comment]
Submitted a PR (#71) to address these two issues.  Not sure how to close issue in GitHub after commit.

**Comment by jonwis** [comment]
Thanks!
