### ISSUE TITLE
Suppressing static initializers causes the fallback telemetry provider callback to not be called

### ISSUE THREAD

**Issue by docjay** [microsoft/wil#76]
Repro steps:
1. Define RESULT_SUPPRESS_STATIC_INITIALIZERS
2. Include wil headers after the define
3. Use SetResultTelemetryFallback to set a telemetry provider callback 
4. Use an error macro (e.g. throw and catch using CATCH_LOG)

Expected: the telemetry callback should be hit
Actual: callback is not hit

Narrowed it down to the following line never being called in result.h
            g_pfnGetContextAndNotifyFailure = GetContextAndNotifyFailure;
WilInitialize_Result should make the global assignment and consumers should invoke WilInitialize_Result. (In the event that static initializers are disabled)

**Comment by dunhor** [comment]
Your assessment is correct. By defining `RESULT_SUPPRESS_STATIC_INITIALIZERS`, you are assuming responsibility for calling the proper initialization functions yourself. In this case it means calling `WilInitialize_Result` from `main`/`DllMain`.

**Comment by docjay** [comment]
WilInitialize_Result is missing the assignment which is the bug I'm calling out

**Comment by dunhor** [comment]
Ahh, I see. I suppose that any existing consumers of `SetResultTelemetryFallback` don't define `RESULT_SUPPRESS_STATIC_INITIALIZERS` (there are very few today; it's primarily intended for consumers who can't link against a CRT). In that case I'd agree - it should ideally be set when given a 'create' command

**Comment by ChrisGuzak** [comment]
looks like this is resolved so I'll mark this closed.
