### ISSUE TITLE
Persistent IntelliSense "cannot deduce auto" error when opening solution which uses WIL

### ISSUE THREAD

**Issue by sylveon** [microsoft/wil#78]
When loading a Visual Studio solution which uses WIL, I always get this IntelliSense error:
![image](https://user-images.githubusercontent.com/6440374/62405626-bc7ecc80-b56d-11e9-8c1b-866747869143.png)

The error does not goes away until I manually open the safecast.h header in the editor, at which points it just disappears until the next time I open the solution.

**Comment by jonwis** [comment]
FWIW, the line in question appears to be this:

```c++
template<typename OldT, typename NewT> constexpr auto intsafe_conversion = nullptr;
```

This appears to fix it:

```c++
template<typename OldT, typename NewT> constexpr nullptr_t intsafe_conversion = nullptr;
```

**Comment by dunhor** [comment]
If you haven't already, make sure that you report Visual Studio bugs to https://developercommunity.visualstudio.com

**Comment by sylveon** [comment]
The PR has been merged so I'll close this issue. I'll still look into what exactly triggers this error and fill appropriate feedback.
