### ISSUE TITLE
_nothrow and failfast

### ISSUE THREAD

**Issue by vkrzv** [microsoft/wil#85]
Hi,

I would like to use a wrapper for Win32 Event in the code of some "optional" plugin for some application. (Imagine Visual Studio and its Intellisense feature as an example of such application). I would not like to fail the whole app if something goes wrong with this plugin. I would prefer to just gracefully stop the plugin instead.
For this reason I tried to use the "_nothrow" flavor of this wrapper:
wil::unique_event_nothrow evt;

But while reading its code I noticed that it can still fail the whole app with failfast if, for example, I call evt.SetEvent without creating the event first.
I would like to handle such failures in some other way rather than failing the application with failfast.
Don't you consider this behavior as inconsistent and unexpected for the _nothrow flavors of the API?

**Comment by ChrisGuzak** [comment]
these fail fasts exist to detect bugs so you can fix them. when writing plugins, where you can impact a system like visual studio, you need to write high quality code. the fail fasts will help you do that.
