### ISSUE TITLE
Update fail fast handling (FAIL_FAST, FAIL_FAST_IF, etc.) to use RoFailFastWithErrorContext to improve diagnosis of failures and Watson bucketing

### ISSUE THREAD

**Issue by ChrisGuzak** [microsoft/wil#91]
There has been feedback that WIL FailFast should use stowed exceptions to get better blaming.  This indeed could be useful as part of FAIL_FAST_IF_FAILED calls.

In addition, the POF logic could also be useful as in the FAIL_FAIL_FAST_IF_FAILED calls that did RoOriginate, you can end up with a crash dump from the point where it actually failed.

We should rationalize what the best way to achieve this is (i.e. this could be just calling RoFailFastWithErrorContext as part of wil/result_originate.h if there is a stowed exception).

**Comment by ChrisGuzak** [comment]
> Manodasan 
To get the ideal behavior is have WIL fail fast check whether there is any stowed exception data available and if so then call RoFailFast.  If not continue to do what it does today.  The main reason why this change hasn’t been done already is it needs to be done in an ODR and layering compliant way.

**Comment by ChrisGuzak** [comment]
the copy of wil in the OS has been updated to address this. the next merge will bring this to this copy.

**Comment by sylveon** [comment]
Any chance to know when the next merge will happen? I'm interested in doing this myself for my roll-your-own error handling code.

**Comment by dunhor** [comment]
@sylveon I'm currently working on it - I like to wait for a successful OS build before bringing back any build fixes, but there are currently some unrelated breaks being worked through. If you want, you can take a look at the current state of the 'dunhor/apt7' branch, which should have most changes copied over.

**Comment by dunhor** [comment]
In particular, the change you are looking for is here: https://github.com/microsoft/wil/blob/b64b5eeb92fc69ee8f6e51d758729681cf11c7d4/include/wil/result_originate.h#L90

**Comment by sylveon** [comment]
Thank you!
