### ISSUE TITLE
Best practices for using com_ptr to create factory objects?

### ISSUE THREAD

**Issue by zomgrolf** [microsoft/wil#92]
Hi,
I'm sorry for asking such a basic question, but I'm back to using COM APIs after a decade-long break and trying to adjust to modern best practices.

I'm working on some code that uses Direct2D and I'm looking at WIL to help me with that.

What are the recommended best practices for using `com_ptr` when calling functions like `D2D1CreateFactory` or `DWriteCreateFactory`? The former uses `void**` as the type of the output parameter, the latter `IUnknown**`. I've been following the examples in the docs for Direct2D and DirectWrite and using `reinterpret_cast` -- that seems to work well after upgrading to `com_ptr`, and looking at the source code there's nothing indicating that there's a better alternative for:
```
wil::com_ptr<IDWriteFactory2> pDWriteFactory2;
DWriteCreateFactory(
    DWRITE_FACTORY_TYPE_SHARED, 
    __uuidof(IDWriteFactory2), 
    reinterpret_cast<IUnknown**>(&pDWriteFactory2));
```
but I might be missing something... I think earlier incarnations of smart COM pointers had methods like `put_void` for getting the underlying pointer cast to `void**` for purposes like this. Just wanted to make sure there's no better way of doing things that I had somehow missed...

My other question is: how to use `wil::CoCreateInstance` to obtain a WIC factory object that implements `IWICImagingFactory2`? The first template argument expects a class, from which it can extract the CLSID using `__uuidof`, but in this case I only have the GUID `CLSID_WICImagingFactory2`. Is it a supported scenario, or should I not even bother and stick to the old way of doing things?

**Comment by sylveon** [comment]
I've created #93 which adds `put_void()` and `put_unknown()` to `com_ptr` and allows you to pass a CLSID to `wil::CoCreateInstance`.

**Comment by zomgrolf** [comment]
Wow, that was quick, awesome!
I like the new overloads for `CoCreateInstance` -- now my code will look much nicer.

The new `put_void` member fn matches other smart COM pointers, so it makes transition a bit easier, so that's also nice. I wonder about `put_unknown` -- IUnknown is the base interface, but in some cases com calls do return other interfaces, e.g. `ID2D1Factory::CreateWicBitmapRenderTarget` returns `ID2D1RenderTarget`, where you might actually want to hold `ID2D1BitmapRenderTarget`. So, I'm thinking it might be better to have a member function template, say `put_as<T>` (with a better name though!), that does the `reinterpret_cast`, possibly with an extra check to ensure that `T` is the base class of whatever interface is held by the smart pointer?

**Comment by sylveon** [comment]
Wow talk about consistency :/
Since this is still a PR, would you be fine with just `put_as<void>` instead of `put_void`?

**Comment by zomgrolf** [comment]
Absolutely! Whatever you think is best.
Just pointing out, that a separate `put_void` is consistent with `com_ptr::put_void` in WinRT, so that's one less search & replace when switching between the two. Personally, I don't care about that (at all), so feel free to get rid of it...

**Comment by sylveon** [comment]
> but in some cases com calls do return other interfaces, e.g. `ID2D1Factory::CreateWicBitmapRenderTarget` returns `ID2D1RenderTarget`, where you might actually want to hold `ID2D1BitmapRenderTarget`.

After rereading don't think this is a great idea. You should use an `wil::com_ptr<ID2D1RenderTarget>` and use `QueryInterface` after the call to make sure it is actually an `ID2D1BitmapRenderTarget`, because you never know when that implementation detail may be changed.

**Comment by zomgrolf** [comment]
That's a very good point! In that case, there's nothing else to be added to your fix, I think.
Thanks!
