### ISSUE TITLE
Add a RETURN_IF_FALSE macro

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/wil#98]
I'm curious if there's a reason there's no `RETURN_IF_FALSE` macro in result_macros.h. Our use-case is early returning `false` if a function call returned `false` in a simple one-liner.

The nearest equivalent is `RETURN_IF_WIN32_BOOL_FALSE`, but that returns the value of GLE, not the bool itself.

https://github.com/microsoft/wil/blob/30c476856fb4f45772979d9f4caf807abf43122c/include/wil/result_macros.h#L605

The implementation we've been using is as follows
```c++
#define RETURN_IF_FALSE(b)                    \
    do                                        \
    {                                         \
        BOOL __boolRet = wil::verify_bool(b); \
        if (!__boolRet)                       \
        {                                     \
            return b;                         \
        }                                     \
    } while (0, 0)
```

Though it looks like there might be some other warning suppression that might need to be included, since this was inspired by an older version of wil. If there's no objection, I'm happy to open a PR 😄

**Comment by dunhor** [comment]
For one, you are double evaluating the expression above (should be `return __boolRet` instead), but that's a minor issue, of course.

But anyway, it seems like it would be too easy to mis-use. All non-prefixed macros are generally assumed to be `HRESULT`-based. E.g. it seems like this would be too easy to assume functionality similar to `RETURN_IF_WIN32_BOOL_FALSE` and expect it to return something like `HRESULT_FROM_WIN32(::GetLastError())`, but in fact it's returning `0` (`S_OK`). Perhaps a name more like `RETURN_BOOL_IF_FALSE` would be more appropriate.

There's also some ambiguity as to whether or not any logging, etc. will occur. E.g. when the result of the expression is false, does `GetLastError` get called and logged?

I'd suggest bringing up the suggestion with the internal WIL discussion alias to get more feedback. I know that there was interest in adding `NTSTATUS`-focused macros a while ago; perhaps there's similar interest in `BOOL`-forwarding macros. FWIW, IIRC the proposed naming for `NTSTATUS` codes was to prefix with `NT_`, so `NT_RETURN_IF`, etc.)

**Comment by dunhor** [comment]
Closing since feedback seems pretty unanimous not to add this
