### ISSUE TITLE
GDI object leak in unique_hdc_paint?

### ISSUE THREAD

**Issue by rysavyjan** [microsoft/wil#99]
It looks like there is a leak in ```wil::unique_hdc_paint```, ::EndPaint() is called with nullptr instead of HWND handle. Am I doing something wrong?

Repo: https://github.com/rysavyjan/wil_paint_leak

```cpp
LRESULT CALLBACK WindowProc(HWND hwnd, UINT uMsg, WPARAM wParam, LPARAM lParam)
{
	switch (uMsg)
	{
	case WM_DESTROY:
		PostQuitMessage(0);
		return 0;

	case WM_PAINT:
	{
		PAINTSTRUCT ps;
		wil::unique_hdc_paint hDC = wil::BeginPaint(hwnd, &ps);
		FillRect(hDC.get(), &ps.rcPaint, (HBRUSH)(COLOR_WINDOW + 1));
		InvalidateRect(hwnd, NULL, FALSE); // request another paint
		Sleep(1);
		return 0;
	}
	return 0;
	}

	return DefWindowProc(hwnd, uMsg, wParam, lParam);
}
```

![image](https://user-images.githubusercontent.com/46950152/66131938-8f45ad80-e5f4-11e9-9882-84845a03a56f.png)

![image](https://user-images.githubusercontent.com/46950152/66132148-eba8cd00-e5f4-11e9-8d9a-e8020558f29b.png)

**Comment by sylveon** [comment]
I've created #100 to resolve your issue.
